
# STS-B first-demo score-anchor causal intervention with SAE features

This notebook tests a **continuous STS-B causal analogue** of the DPS idea, focused on whether steering a candidate SAE feature moves the model's numeric STS prediction **toward the first demonstration's score**.

For a fixed STS-B test query with gold score \(y\), we construct parallel prompts where only the first demonstration's similarity-score anchor varies:

\[
s \in \{0,1,2,3,4,5\}.
\]

For each prompt, we first compute the baseline expected score \(\hat y_{\mathrm{base}}\). Then, for each candidate feature \(f\), we add its SAE decoder direction at a selected token span and compute the steered expected score \(\hat y_{\mathrm{steer}}\). The main causal diagnostic is whether the score shift

\[
\Delta \hat y_f = \hat y_{\mathrm{steer}} - \hat y_{\mathrm{base}}
\]

points toward the first demonstration's score:

\[
s - \hat y_{\mathrm{base}}.
\]

The key summary is the within-query correlation:

\[
\rho_{i,f} = \mathrm{corr}_s\left(\Delta \hat y_f(p_{i,s}),\; s - \hat y_{\mathrm{base}}(p_{i,s})\right).
\]

A positive value means steering feature \(f\) tends to pull the model's prediction in the direction of the first demonstration's numeric score.

The notebook evaluates four steering spans:

1. `all_query_tokens`: all final test-query sentence-pair tokens.
2. `last_query_token`: only the final token in the final test-query sentence-pair span.
3. `assistant_generation_prefix_token`: tokens in the final assistant-generation prefix, i.e. the prediction-adjacent assistant prefix.
4. `last_prompt_token`: only the final rendered prompt token.

Each SAE feature is steered **one at a time**, never jointly.

In [2]:
import os
os.environ['HF_TOKEN'] = "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"
os.environ['HUGGINGFACEHUB_API_TOKEN'] = "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"

In [3]:
import plotly.io as pio

# Try this first for standard Jupyter Notebooks
pio.renderers.default = "notebook"

In [1]:

# ============================================================
# Imports and configuration
# ============================================================

import os
import re
import gc
import json
import math
import random
import warnings
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from IPython.display import display
from datasets import load_dataset
from huggingface_hub import hf_hub_download
from transformers import AutoModelForCausalLM, AutoTokenizer
from tqdm.auto import tqdm

import plotly.graph_objects as go

warnings.filterwarnings("ignore")

# -----------------------------
# Reproducibility
# -----------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# -----------------------------
# Model / SAE
# -----------------------------
MODEL_NAME = "Qwen/Qwen3-0.6B"
MODEL_SHORT_NAME = "Qwen3-0.6B-IT"
TARGET_LAYER = 14
SAE_REPO_ID = "japhba/qwen3-0.6b-saes"
SAE_BASE_DIR = "saes_Qwen_Qwen3-0.6B_batch_top_k"
SAE_TRAINER = "trainer_0"
SAE_FILENAME = f"{SAE_BASE_DIR}/resid_post_layer_{TARGET_LAYER}/{SAE_TRAINER}/ae.pt"

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DTYPE = torch.bfloat16 if torch.cuda.is_available() else torch.float32

# -----------------------------
# STS-B causal experiment
# -----------------------------
# Number of fixed test queries sampled approximately uniformly across score anchors.
CAUSAL_N_TEST_QUERIES_TOTAL = 160

# Score anchors used to vary the first demonstration.
QUERY_SCORE_ANCHORS = [0, 1, 2, 3, 4, 5]
VARIABLE_DEMO_SCORE_ANCHORS = [0, 1, 2, 3, 4, 5]
N_VARIABLE_DEMOS_PER_ANCHOR = 1

# One variable first demo + M-1 fixed demos.
NUM_DEMOS_TOTAL = 6

# Numeric STS score range.
SCORE_MIN = 0.0
SCORE_MAX = 5.0
SCORE_FORMAT_DECIMALS = 1

# Candidate scores used to convert model logits into an expected numeric prediction.
# Smaller step => more faithful but slower because every prompt is scored against more strings.
SCORE_CANDIDATE_STEP = 0.5
SCORE_CANDIDATE_VALUES = [round(float(x), 1) for x in np.arange(SCORE_MIN, SCORE_MAX + 1e-9, SCORE_CANDIDATE_STEP)]
LENGTH_NORMALIZE_SCORE_LOGPROBS = False

# Candidate SAE features to causally test.
# Set to None to auto-load the top discovery features from the previous STS-B proximity notebook.
# Otherwise, put a Qwen3-0.6B feature list such as: CANDIDATE_FEATURES = [1234, 5678, 9012]
CANDIDATE_FEATURES = [4724, 6396, 3901, 6537, 4140, ]
N_CANDIDATE_FEATURES_FROM_DISCOVERY = 20
FALLBACK_CANDIDATE_FEATURES = [
    # Optional Qwen3-0.6B fallback feature indices.
    # Leave empty to force loading from the Qwen3-0.6B discovery notebook output.
    # Example: 1234, 5678,
]

# Positive alpha adds the feature's SAE decoder direction to selected hidden states.
CAUSAL_ALPHA_VALUES = [10.0]
NORMALIZE_STEERING_DIRECTION = True

# Steering spans to evaluate.
# - all_query_tokens: all final test sentence-pair tokens.
# - last_query_token: only the last final-query token.
# - assistant_generation_prefix_token: final assistant-generation prefix tokens.
# - last_prompt_token: only the final rendered prompt token.
CAUSAL_INTERVENTION_TOKEN_MODES = [
    "all_query_tokens",
    "last_query_token",
    "assistant_generation_prefix_token",
    "last_prompt_token",
]

MAX_DEMO_CHARS = 500
MAX_QUERY_CHARS = 600
MAX_PROMPT_TOKENS = 4096
SCORE_BATCH_SIZE = 8

# Effect-size summaries.
# For the anchor-pull causal analysis, very small baseline-to-anchor distances are noisy:
# if |first-demo score - baseline expected score| is already <= 0.5, tiny score-estimation
# errors can flip the apparent direction. We therefore report the main anchor-pull
# summaries only on conditions with distance >= 1.0, and use fine-grained bins
# [1,1.5), [1.5,2), [2,2.5), [2.5,3), [3,3.5), ... for the distance plot.
ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS = 1.0
ANCHOR_PULL_DISTANCE_BIN_EDGES = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, np.inf]
ANCHOR_PULL_DISTANCE_BIN_LABELS = [
    "1–1.5",
    "1.5–2",
    "2–2.5",
    "2.5–3",
    "3–3.5",
    "3.5–4",
    "4–4.5",
    "≥4.5",
]
# Retained for secondary diagnostics.
CLOSE_DISTANCE_THRESHOLD = 0.75
FAR_DISTANCE_THRESHOLD = 2.50
CAUSAL_SUCCESS_TOL = 1e-12
TOP_K_FEATURES_TO_DISPLAY = 30

PROMPT_FORMAT_NAME = "format2_wrapped_user_assistant_demos_numeric_sts_prediction"
OUTPUT_ROOT = Path("./sts_b_proximity_outputs_qwen3_0_6b")
DISCOVERY_RESULT_DIR = OUTPUT_ROOT / "stsb_score_proximity" / f"layer_{TARGET_LAYER}" / "lastk_-1"
RESULT_DIR = OUTPUT_ROOT / "stsb_score_anchor_pull_causal" / f"layer_{TARGET_LAYER}"
RESULT_DIR.mkdir(parents=True, exist_ok=True)

# Cache versioning guard.
# This tag is deliberately derived from prompt-plan-defining settings so that changing
# CAUSAL_N_TEST_QUERIES_TOTAL, anchors, demo count, score grid, seed, etc. cannot reuse
# stale baseline/steered prediction caches from an older run.
def _cache_value_tag(x):
    return str(x).replace(" ", "").replace(".", "p").replace("-", "m").replace(",", "_").replace("[", "").replace("]", "")

CAUSAL_PLAN_CACHE_TAG = (
    f"seed{SEED}"
    f"__nq{CAUSAL_N_TEST_QUERIES_TOTAL}"
    f"__demos{NUM_DEMOS_TOTAL}"
    f"__q{_cache_value_tag(QUERY_SCORE_ANCHORS)}"
    f"__v{_cache_value_tag(VARIABLE_DEMO_SCORE_ANCHORS)}"
    f"__nv{N_VARIABLE_DEMOS_PER_ANCHOR}"
    f"__step{_cache_value_tag(SCORE_CANDIDATE_STEP)}"
)

SCORE_CACHE_DIR = RESULT_DIR / "score_prediction_cache" / CAUSAL_PLAN_CACHE_TAG
SCORE_CACHE_DIR.mkdir(parents=True, exist_ok=True)

print("MODEL:", MODEL_SHORT_NAME)
print("TARGET_LAYER:", TARGET_LAYER)
print("SAE:", SAE_REPO_ID, SAE_FILENAME)
print("DISCOVERY_RESULT_DIR:", DISCOVERY_RESULT_DIR)
print("RESULT_DIR:", RESULT_DIR)
print("CAUSAL_PLAN_CACHE_TAG:", CAUSAL_PLAN_CACHE_TAG)
print("SCORE_CACHE_DIR:", SCORE_CACHE_DIR)
print("Score candidates:", SCORE_CANDIDATE_VALUES)
print("Token modes:", CAUSAL_INTERVENTION_TOKEN_MODES)

MODEL: Qwen3-0.6B-IT
TARGET_LAYER: 14
SAE: japhba/qwen3-0.6b-saes saes_Qwen_Qwen3-0.6B_batch_top_k/resid_post_layer_14/trainer_0/ae.pt
DISCOVERY_RESULT_DIR: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_proximity/layer_14/lastk_-1
RESULT_DIR: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14
CAUSAL_PLAN_CACHE_TAG: seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5
SCORE_CACHE_DIR: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5
Score candidates: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
Token modes: ['all_query_tokens', 'last_query_token', 'assistant_generation_prefix_token', 'last_prompt_token']

In [4]:

# ============================================================
# Robust HF loaders + Qwen BatchTopK SAE wrapper
# ============================================================

HF_TOKEN = (
    os.environ.get("HF_TOKEN")
    or os.environ.get("HUGGING_FACE_HUB_TOKEN")
    or os.environ.get("HUGGINGFACEHUB_API_TOKEN")
    or None
)

if HF_TOKEN is None:
    print("Warning: HF_TOKEN is not set. Public resources may still load, but gated/rate-limited resources may fail.")
else:
    print("HF_TOKEN detected from environment.")


def hf_hub_download_robust(repo_id: str, filename: str, repo_type: Optional[str] = None) -> str:
    kwargs = {"repo_id": repo_id, "filename": filename}
    if repo_type is not None:
        kwargs["repo_type"] = repo_type
    if HF_TOKEN is not None:
        kwargs["token"] = HF_TOKEN
    try:
        return hf_hub_download(**kwargs)
    except TypeError:
        kwargs.pop("token", None)
        if HF_TOKEN is not None:
            kwargs["use_auth_token"] = HF_TOKEN
        return hf_hub_download(**kwargs)


def load_tokenizer_robust(model_name: str):
    kwargs = {
        "pretrained_model_name_or_path": model_name,
        "trust_remote_code": True,
        "use_fast": True,
    }
    if HF_TOKEN is not None:
        kwargs["token"] = HF_TOKEN
    try:
        tok = AutoTokenizer.from_pretrained(**kwargs)
    except TypeError:
        kwargs.pop("token", None)
        if HF_TOKEN is not None:
            kwargs["use_auth_token"] = HF_TOKEN
        tok = AutoTokenizer.from_pretrained(**kwargs)
    return tok


def load_model_robust(model_name: str):
    kwargs = {
        "pretrained_model_name_or_path": model_name,
        "torch_dtype": DTYPE,
        "trust_remote_code": True,
    }
    if torch.cuda.is_available():
        kwargs["device_map"] = "auto"
    if HF_TOKEN is not None:
        kwargs["token"] = HF_TOKEN
    try:
        mdl = AutoModelForCausalLM.from_pretrained(**kwargs)
    except TypeError:
        kwargs.pop("token", None)
        if HF_TOKEN is not None:
            kwargs["use_auth_token"] = HF_TOKEN
        mdl = AutoModelForCausalLM.from_pretrained(**kwargs)
    mdl.eval()
    try:
        mdl.config.use_cache = False
    except Exception:
        pass
    return mdl


def _load_dataset_attempt(path: str, config_name: Optional[str] = None, split_spec=None):
    base_kwargs = {"path": path}
    if config_name is not None:
        base_kwargs["name"] = config_name
    if split_spec is not None:
        base_kwargs["split"] = split_spec
    if HF_TOKEN is not None:
        base_kwargs["token"] = HF_TOKEN

    attempts = []
    attempts.append(dict(base_kwargs))
    kw = dict(base_kwargs)
    kw["trust_remote_code"] = True
    attempts.append(kw)

    if HF_TOKEN is not None:
        kw = dict(base_kwargs)
        kw.pop("token", None)
        kw["use_auth_token"] = HF_TOKEN
        attempts.append(kw)

    last_error = None
    for kwargs in attempts:
        try:
            return load_dataset(**kwargs)
        except TypeError as e:
            last_error = e
            kwargs2 = dict(kwargs)
            kwargs2.pop("trust_remote_code", None)
            kwargs2.pop("token", None)
            try:
                return load_dataset(**kwargs2)
            except Exception as e2:
                last_error = e2
        except Exception as e:
            last_error = e
    raise last_error


class QwenBatchTopKSAE(torch.nn.Module):
    """Minimal wrapper for Qwen3 BatchTopK SAE checkpoints."""

    def __init__(self, state_dict, device=DEVICE, dtype=DTYPE):
        super().__init__()
        self.device = torch.device(device)
        self.dtype = dtype

        if isinstance(state_dict, dict) and "state_dict" in state_dict:
            state_dict = state_dict["state_dict"]
        if isinstance(state_dict, dict) and "model" in state_dict and isinstance(state_dict["model"], dict):
            state_dict = state_dict["model"]

        b_dec = state_dict["b_dec"].detach()
        b_enc = state_dict.get("encoder.bias", state_dict.get("b_enc")).detach()
        enc_w = state_dict.get("encoder.weight", state_dict.get("W_enc")).detach()
        dec_w = state_dict.get("decoder.weight", state_dict.get("W_dec")).detach()
        threshold = state_dict.get("threshold", torch.tensor(0.0))
        threshold = threshold.detach() if torch.is_tensor(threshold) else torch.tensor(threshold)
        k = state_dict.get("k", None)
        if torch.is_tensor(k):
            k = int(k.item())

        d_model = int(b_dec.numel())
        n_features = int(b_enc.numel())

        if enc_w.shape == (n_features, d_model):
            W_enc = enc_w.T.contiguous()
        elif enc_w.shape == (d_model, n_features):
            W_enc = enc_w.contiguous()
        else:
            raise ValueError(f"Unexpected encoder.weight shape {tuple(enc_w.shape)}")

        if dec_w.shape == (d_model, n_features):
            W_dec = dec_w.T.contiguous()
        elif dec_w.shape == (n_features, d_model):
            W_dec = dec_w.contiguous()
        else:
            raise ValueError(f"Unexpected decoder.weight shape {tuple(dec_w.shape)}")

        self.register_buffer("W_enc", W_enc.to(device=self.device, dtype=self.dtype))
        self.register_buffer("W_dec", W_dec.to(device=self.device, dtype=self.dtype))
        self.register_buffer("b_enc", b_enc.to(device=self.device, dtype=self.dtype))
        self.register_buffer("b_dec", b_dec.to(device=self.device, dtype=self.dtype))
        self.register_buffer("threshold", threshold.to(device=self.device, dtype=self.dtype))
        self.k = k
        self.d_model = d_model
        self.n_features = n_features

    def process_sae_in(self, x: torch.Tensor) -> torch.Tensor:
        return x - self.b_dec

    def encode_pre(self, x: torch.Tensor) -> torch.Tensor:
        x = x.to(device=self.device, dtype=self.dtype)
        return self.process_sae_in(x) @ self.W_enc + self.b_enc

    def activation_fn(self, pre: torch.Tensor) -> torch.Tensor:
        return torch.where(pre > self.threshold, pre, torch.zeros_like(pre))

    def encode(self, x: torch.Tensor) -> torch.Tensor:
        return self.activation_fn(self.encode_pre(x))


def get_model_input_device(model) -> torch.device:
    return model.get_input_embeddings().weight.device


def get_layer_device(model, layer_idx: int) -> torch.device:
    block = model.get_submodule(f"model.layers.{layer_idx}")
    try:
        return next(block.parameters()).device
    except StopIteration:
        return get_model_input_device(model)

HF_TOKEN detected from environment.

In [5]:

# ============================================================
# Load STS-B / STSBenchmark data, model, tokenizer, and SAE
# ============================================================

STSB_DATASET_CANDIDATES = [
    ("SetFit/stsb", None),
    ("sentence-transformers/stsb", None),
    ("mteb/stsbenchmark-sts", None),
    ("glue", "stsb"),
]

SENTENCE1_CANDIDATES = [
    "sentence1", "sentence_1", "sent1", "text1", "text_a", "sentence_a",
    "sentence_A", "query1", "question1",
]
SENTENCE2_CANDIDATES = [
    "sentence2", "sentence_2", "sent2", "text2", "text_b", "sentence_b",
    "sentence_B", "query2", "question2",
]
SCORE_CANDIDATES = [
    "label", "score", "similarity_score", "gold_score", "labels", "similarity",
]


def _find_first_existing_column(columns, candidates):
    cols = list(columns)
    lower_to_original = {str(c).lower(): c for c in cols}
    for cand in candidates:
        if cand in cols:
            return cand
        if cand.lower() in lower_to_original:
            return lower_to_original[cand.lower()]
    return None


def _load_stsb_dataset():
    last_error = None
    for path, config_name in STSB_DATASET_CANDIDATES:
        try:
            print(f"Trying STS dataset: path={path!r}, config={config_name!r}")
            ds = _load_dataset_attempt(path, config_name, split_spec=None)
            if not hasattr(ds, "keys"):
                raise RuntimeError("Expected a DatasetDict-like object.")
            print("Loaded dataset:", path, config_name, "splits:", list(ds.keys()))
            return ds, f"{path}" if config_name is None else f"{path}:{config_name}"
        except Exception as e:
            last_error = e
            print("  failed:", repr(e))
    raise RuntimeError(f"Failed to load any STS-B candidate. Last error: {last_error}")


def normalize_stsb_split_to_df(split, split_name: str) -> pd.DataFrame:
    columns = list(getattr(split, "column_names", []))
    s1_col = _find_first_existing_column(columns, SENTENCE1_CANDIDATES)
    s2_col = _find_first_existing_column(columns, SENTENCE2_CANDIDATES)
    score_col = _find_first_existing_column(columns, SCORE_CANDIDATES)
    if s1_col is None or s2_col is None or score_col is None:
        raise KeyError(
            f"Could not identify STS columns in split {split_name}. "
            f"columns={columns}, s1={s1_col}, s2={s2_col}, score={score_col}"
        )
    df = pd.DataFrame({
        "sentence1": [str(x) for x in split[s1_col]],
        "sentence2": [str(x) for x in split[s2_col]],
        "score": pd.to_numeric(split[score_col], errors="coerce"),
    })
    df = df.dropna(subset=["sentence1", "sentence2", "score"]).reset_index(drop=True)

    # Some mirrors normalize scores to [0, 1]. Convert to the standard [0, 5] scale if needed.
    if df["score"].max() <= 1.01 and df["score"].min() >= -0.01:
        print(f"Split {split_name}: detected [0,1]-scaled scores; multiplying by 5.")
        df["score"] = df["score"] * 5.0

    df["score"] = df["score"].clip(SCORE_MIN, SCORE_MAX)
    df["split"] = split_name
    return df


def choose_train_eval_splits(ds):
    if "train" not in ds:
        raise KeyError(f"No train split found. Available splits: {list(ds.keys())}")
    train_split = ds["train"]

    # Prefer validation/dev because many GLUE-style test splits lack usable gold labels.
    for name in ["validation", "dev", "test"]:
        if name in ds:
            eval_split = ds[name]
            return train_split, eval_split, name
    raise KeyError(f"No validation/dev/test split found. Available splits: {list(ds.keys())}")


def clean_text(text: str, max_chars: Optional[int]) -> str:
    text = str(text).replace("\n", " ").replace("\t", " ").strip()
    text = re.sub(r"\s+", " ", text)
    if max_chars is not None and len(text) > int(max_chars):
        text = text[: int(max_chars)].rstrip() + "..."
    return text


def score_anchor(score: float, anchors: Sequence[float]) -> float:
    anchors = np.asarray(anchors, dtype=float)
    return float(anchors[np.argmin(np.abs(anchors - float(score)))])


stsb_ds, DATASET_NAME = _load_stsb_dataset()
train_split, eval_split, EVAL_SPLIT_NAME = choose_train_eval_splits(stsb_ds)
train_df = normalize_stsb_split_to_df(train_split, "train")
eval_df = normalize_stsb_split_to_df(eval_split, EVAL_SPLIT_NAME)

print("Dataset:", DATASET_NAME)
print("Train size:", len(train_df), "Eval split:", EVAL_SPLIT_NAME, "Eval size:", len(eval_df))
print("Train score summary:")
display(train_df["score"].describe().to_frame().T)
print("Eval score summary:")
display(eval_df["score"].describe().to_frame().T)

print("Loading tokenizer...")
tokenizer = load_tokenizer_robust(MODEL_NAME)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

print("Loading model...")
model = load_model_robust(MODEL_NAME)
MODEL_INPUT_DEVICE = get_model_input_device(model)
TARGET_LAYER_DEVICE = get_layer_device(model, TARGET_LAYER)
print("MODEL_INPUT_DEVICE:", MODEL_INPUT_DEVICE)
print("TARGET_LAYER_DEVICE:", TARGET_LAYER_DEVICE)

print("Loading SAE...")
sae_path = hf_hub_download_robust(SAE_REPO_ID, SAE_FILENAME)
try:
    sae_state = torch.load(sae_path, map_location="cpu", weights_only=True)
except TypeError:
    sae_state = torch.load(sae_path, map_location="cpu")
sae = QwenBatchTopKSAE(sae_state, device=TARGET_LAYER_DEVICE, dtype=DTYPE)
sae.eval()
print(f"Loaded SAE: d_model={sae.d_model}, n_features={sae.n_features}, k={sae.k}")

Trying STS dataset: path='SetFit/stsb', config=None

Repo card metadata block was not found. Setting CardData to empty.

Loaded dataset: SetFit/stsb None splits: ['train', 'validation', 'test']
Dataset: SetFit/stsb
Train size: 5749 Eval split: validation Eval size: 1500
Train score summary:

        count      mean       std  min  25%  50%  75%  max
score  5749.0  2.700999  1.464398  0.0  1.5  3.0  3.8  5.0

Eval score summary:

        count      mean       std  min  25%   50%  75%  max
score  1500.0  2.363908  1.500486  0.0  1.0  2.55  3.6  5.0

Loading tokenizer...
Loading model...

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

MODEL_INPUT_DEVICE: cuda:0
TARGET_LAYER_DEVICE: cuda:0
Loading SAE...
Loaded SAE: d_model=1024, n_features=8192, k=80

In [6]:

# ============================================================
# Prompt construction and controlled causal plan
# ============================================================

TASK_INSTRUCTION = (
    "You are an expert at semantic textual similarity. Given two sentences, "
    "output a real-valued similarity score from 0.0 to 5.0, where 0.0 means "
    "the sentences are completely unrelated and 5.0 means the sentences are semantically equivalent. "
    "Respond only with the numeric score."
)

QUERY_START_SENTINEL = "ZXQ_STSB_CAUSAL_QUERY_START_6bb1d99a"
QUERY_END_SENTINEL = "ZXQ_STSB_CAUSAL_QUERY_END_6bb1d99a"


def format_score(score: float) -> str:
    return f"{float(score):.{int(SCORE_FORMAT_DECIMALS)}f}"


def format_sts_user(record: Dict[str, Any], example_idx: int, *, mark_query: bool = False) -> str:
    s1 = clean_text(record["sentence1"], MAX_QUERY_CHARS if mark_query else MAX_DEMO_CHARS)
    s2 = clean_text(record["sentence2"], MAX_QUERY_CHARS if mark_query else MAX_DEMO_CHARS)
    if mark_query:
        # The intervention span covers the final sentence pair, not the answer field.
        body = (
            f"{QUERY_START_SENTINEL}Sentence 1:\n{s1}\n"
            f"Sentence 2:\n{s2}{QUERY_END_SENTINEL}\n"
            f"Similarity score:"
        )
    else:
        body = (
            f"Sentence 1:\n{s1}\n"
            f"Sentence 2:\n{s2}\n"
            f"Similarity score:"
        )
    return f"Example {example_idx}\n{body}"


def manual_qwen_chat_template(messages: List[Dict[str, str]], add_generation_prompt: bool = False) -> str:
    parts = []
    for msg in messages:
        parts.append(f"<|im_start|>{msg['role']}\n{msg['content']}<|im_end|>\n")
    if add_generation_prompt:
        parts.append("<|im_start|>assistant\n")
    return "".join(parts).rstrip()


def apply_qwen_chat_template(messages: List[Dict[str, str]], add_generation_prompt: bool = False) -> str:
    try:
        return tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=add_generation_prompt,
            enable_thinking=False,
        ).rstrip()
    except TypeError:
        try:
            return tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=add_generation_prompt,
            ).rstrip()
        except Exception:
            return manual_qwen_chat_template(messages, add_generation_prompt=add_generation_prompt)
    except Exception:
        return manual_qwen_chat_template(messages, add_generation_prompt=add_generation_prompt)


def render_prompt_with_query_span(messages: List[Dict[str, str]]) -> Tuple[str, Tuple[int, int]]:
    rendered = apply_qwen_chat_template(messages, add_generation_prompt=True)
    s = rendered.find(QUERY_START_SENTINEL)
    e = rendered.find(QUERY_END_SENTINEL)
    if s < 0 or e < 0 or e <= s:
        raise ValueError("Could not locate query sentinels in rendered prompt.")
    query_text_start_marked = s + len(QUERY_START_SENTINEL)
    query_text = rendered[query_text_start_marked:e]
    prompt = rendered[:s] + query_text + rendered[e + len(QUERY_END_SENTINEL):]
    query_char_span = (s, s + len(query_text))
    return prompt.rstrip(), query_char_span


def build_wrapped_sts_prediction_prompt(demos: List[Dict[str, Any]], query: Dict[str, Any]) -> Tuple[str, Tuple[int, int]]:
    messages = [{"role": "system", "content": TASK_INSTRUCTION}]
    for i, demo in enumerate(demos, start=1):
        messages.append({"role": "user", "content": format_sts_user(demo, i, mark_query=False)})
        messages.append({"role": "assistant", "content": format_score(demo["score"])})
    messages.append({"role": "user", "content": format_sts_user(query, len(demos) + 1, mark_query=True)})
    return render_prompt_with_query_span(messages)


def add_anchor_columns(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out["score_anchor"] = [score_anchor(s, QUERY_SCORE_ANCHORS) for s in out["score"].tolist()]
    return out


train_df = add_anchor_columns(train_df)
eval_df = add_anchor_columns(eval_df)


def sample_eval_queries_uniform_by_score(total_n: int, seed: int = SEED) -> pd.DataFrame:
    rng = random.Random(int(seed))
    anchors = list(map(float, QUERY_SCORE_ANCHORS))
    per_anchor = int(total_n) // len(anchors)
    remainder = int(total_n) % len(anchors)
    counts = {a: per_anchor for a in anchors}
    for a in anchors[:remainder]:
        counts[a] += 1

    rows = []
    for anchor in anchors:
        pool = eval_df[eval_df["score_anchor"].eq(anchor)].copy()
        if pool.empty:
            pool = eval_df.assign(_dist=(eval_df["score"] - anchor).abs()).sort_values("_dist").head(max(1, counts[anchor]))
        idx_pool = pool.index.astype(int).tolist()
        n = int(counts[anchor])
        if len(idx_pool) >= n:
            chosen = rng.sample(idx_pool, n)
            with_replacement = False
        else:
            chosen = rng.choices(idx_pool, k=n)
            with_replacement = True
        for idx in chosen:
            rec = eval_df.loc[int(idx)].to_dict()
            rec.update({
                "query_eval_index": int(idx),
                "query_score_anchor": float(anchor),
                "query_sampled_with_replacement": bool(with_replacement),
            })
            rows.append(rec)
    query_df = pd.DataFrame(rows).reset_index(drop=True)
    query_df["query_global_id"] = np.arange(len(query_df), dtype=int)
    return query_df


def sample_train_index_near_anchor(anchor: float, rng: random.Random, exclude: Optional[set] = None) -> int:
    exclude = set(exclude or set())
    candidates = train_df[~train_df.index.isin(exclude)].copy()
    if candidates.empty:
        candidates = train_df.copy()
    pool = candidates[candidates["score_anchor"].eq(float(anchor))].copy()
    if pool.empty:
        pool = candidates.assign(_dist=(candidates["score"] - float(anchor)).abs()).sort_values("_dist").head(100)
    return int(rng.choice(pool.index.astype(int).tolist()))


def sample_fixed_demo_indices(query_global_id: int) -> Tuple[int, ...]:
    rng = random.Random(SEED + 100_000 + 997 * int(query_global_id))
    n_fixed = int(NUM_DEMOS_TOTAL) - 1
    anchors = list(map(float, QUERY_SCORE_ANCHORS))
    fixed_anchor_order = []
    while len(fixed_anchor_order) < n_fixed:
        shuffled = anchors[:]
        rng.shuffle(shuffled)
        fixed_anchor_order.extend(shuffled)
    fixed_anchor_order = fixed_anchor_order[:n_fixed]

    chosen = []
    exclude = set()
    for a in fixed_anchor_order:
        idx = sample_train_index_near_anchor(a, rng, exclude=exclude)
        chosen.append(idx)
        exclude.add(idx)
    rng.shuffle(chosen)
    return tuple(map(int, chosen))


def sample_variable_demo_indices_by_anchor(query_global_id: int, fixed_demo_indices: Sequence[int]) -> Dict[Tuple[float, int], int]:
    out = {}
    exclude_base = set(map(int, fixed_demo_indices))
    for anchor in map(float, VARIABLE_DEMO_SCORE_ANCHORS):
        for rep in range(int(N_VARIABLE_DEMOS_PER_ANCHOR)):
            rng = random.Random(SEED + 200_000 + 10_007 * int(query_global_id) + 1_009 * int(anchor * 10) + rep)
            idx = sample_train_index_near_anchor(anchor, rng, exclude=exclude_base)
            out[(float(anchor), int(rep))] = int(idx)
    return out


def df_row_to_record(df: pd.DataFrame, idx: int) -> Dict[str, Any]:
    r = df.loc[int(idx)]
    return {
        "sentence1": str(r["sentence1"]),
        "sentence2": str(r["sentence2"]),
        "score": float(r["score"]),
        "score_anchor": float(r["score_anchor"]),
    }


def build_score_proximity_causal_plan() -> pd.DataFrame:
    query_df = sample_eval_queries_uniform_by_score(CAUSAL_N_TEST_QUERIES_TOTAL)
    rows = []
    for q in tqdm(query_df.itertuples(index=False), total=len(query_df), desc="Building STS causal prompt plan"):
        qid = int(q.query_global_id)
        query_record = {
            "sentence1": str(q.sentence1),
            "sentence2": str(q.sentence2),
            "score": float(q.score),
            "score_anchor": float(q.query_score_anchor),
        }
        fixed_indices = sample_fixed_demo_indices(qid)
        variable_indices = sample_variable_demo_indices_by_anchor(qid, fixed_indices)
        fixed_records = [df_row_to_record(train_df, idx) for idx in fixed_indices]

        for first_anchor in map(float, VARIABLE_DEMO_SCORE_ANCHORS):
            for rep in range(int(N_VARIABLE_DEMOS_PER_ANCHOR)):
                variable_idx = int(variable_indices[(float(first_anchor), int(rep))])
                first_record = df_row_to_record(train_df, variable_idx)
                demos = [first_record] + fixed_records
                prompt, query_char_span = build_wrapped_sts_prediction_prompt(demos, query_record)
                first_score = float(first_record["score"])
                query_score = float(query_record["score"])
                rows.append({
                    "prompt_row_id": len(rows),
                    "query_global_id": qid,
                    "query_eval_index": int(q.query_eval_index),
                    "query_score": query_score,
                    "query_score_anchor": float(q.query_score_anchor),
                    "query_sampled_with_replacement": bool(q.query_sampled_with_replacement),
                    "first_demo_anchor": float(first_anchor),
                    "first_demo_rep": int(rep),
                    "first_demo_train_index": int(variable_idx),
                    "first_demo_score": first_score,
                    "score_distance": abs(first_score - query_score),
                    "score_proximity": -abs(first_score - query_score),
                    "anchor_score_distance": abs(float(first_anchor) - query_score),
                    "anchor_score_proximity": -abs(float(first_anchor) - query_score),
                    "fixed_demo_indices": tuple(map(int, fixed_indices)),
                    "query_char_span_start": int(query_char_span[0]),
                    "query_char_span_end": int(query_char_span[1]),
                    "prompt": prompt,
                })
    return pd.DataFrame(rows)


causal_prompt_plan_df = build_score_proximity_causal_plan()
expected_prompts = int(CAUSAL_N_TEST_QUERIES_TOTAL) * len(VARIABLE_DEMO_SCORE_ANCHORS) * int(N_VARIABLE_DEMOS_PER_ANCHOR)
assert len(causal_prompt_plan_df) == expected_prompts, (len(causal_prompt_plan_df), expected_prompts)

print("Prompt format:", PROMPT_FORMAT_NAME)
print("N test queries:", causal_prompt_plan_df["query_global_id"].nunique())
print("Total prompts:", len(causal_prompt_plan_df))
print("Expected formula:", f"{CAUSAL_N_TEST_QUERIES_TOTAL} queries × {len(VARIABLE_DEMO_SCORE_ANCHORS)} score anchors × {N_VARIABLE_DEMOS_PER_ANCHOR} reps = {expected_prompts}")
print("Query score-anchor counts:")
display(causal_prompt_plan_df[["query_global_id", "query_score_anchor"]].drop_duplicates()["query_score_anchor"].value_counts().sort_index().to_frame("n_queries"))
print("First-demo score-anchor counts:")
display(causal_prompt_plan_df["first_demo_anchor"].value_counts().sort_index().to_frame("n_prompts"))

plan_light_path = RESULT_DIR / "stsb_causal_prompt_plan_latest.csv"
causal_prompt_plan_df.drop(columns=["prompt"]).to_csv(plan_light_path, index=False)
print("Saved lightweight causal prompt plan:", plan_light_path)

display(causal_prompt_plan_df.drop(columns=["prompt"]).head(10))

Building STS causal prompt plan:   0%|          | 0/160 [00:00<?, ?it/s]

Prompt format: format2_wrapped_user_assistant_demos_numeric_sts_prediction
N test queries: 160
Total prompts: 960
Expected formula: 160 queries × 6 score anchors × 1 reps = 960
Query score-anchor counts:

                    n_queries
query_score_anchor
0.0                        27
1.0                        27
2.0                        27
3.0                        27
4.0                        26
5.0                        26

First-demo score-anchor counts:

                   n_prompts
first_demo_anchor
0.0                      160
1.0                      160
2.0                      160
3.0                      160
4.0                      160
5.0                      160

Saved lightweight causal prompt plan: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/stsb_causal_prompt_plan_latest.csv

,prompt_row_id,query_global_id,query_eval_index,query_score,query_score_anchor,query_sampled_with_replacement,first_demo_anchor,first_demo_rep,first_demo_train_index,first_demo_score,score_distance,score_proximity,anchor_score_distance,anchor_score_proximity,fixed_demo_indices,query_char_span_start,query_char_span_end
0,0,0,835,0.0,0.0,False,0.0,0,5380,0.2,0.2,-0.2,0.0,-0.0,"(5182, 1937, 1466, 2676, 3141)",2021,2217
1,1,0,835,0.0,0.0,False,1.0,0,1019,0.6,0.6,-0.6,1.0,-1.0,"(5182, 1937, 1466, 2676, 3141)",2021,2217
2,2,0,835,0.0,0.0,False,2.0,0,2417,1.8,1.8,-1.8,2.0,-2.0,"(5182, 1937, 1466, 2676, 3141)",1977,2173
3,3,0,835,0.0,0.0,False,3.0,0,5067,3.0,3.0,-3.0,3.0,-3.0,"(5182, 1937, 1466, 2676, 3141)",1982,2178
4,4,0,835,0.0,0.0,False,4.0,0,3860,4.4,4.4,-4.4,4.0,-4.0,"(5182, 1937, 1466, 2676, 3141)",2037,2233
5,5,0,835,0.0,0.0,False,5.0,0,5566,5.0,5.0,-5.0,5.0,-5.0,"(5182, 1937, 1466, 2676, 3141)",2029,2225
6,6,1,127,0.0,0.0,False,0.0,0,365,0.0,0.0,-0.0,0.0,-0.0,"(595, 2105, 1057, 990, 1537)",1459,1551
7,7,1,127,0.0,0.0,False,1.0,0,901,1.0,1.0,-1.0,1.0,-1.0,"(595, 2105, 1057, 990, 1537)",1455,1547
8,8,1,127,0.0,0.0,False,2.0,0,4468,2.2,2.2,-2.2,2.0,-2.0,"(595, 2105, 1057, 990, 1537)",1476,1568
9,9,1,127,0.0,0.0,False,3.0,0,2768,2.8,2.8,-2.8,3.0,-3.0,"(595, 2105, 1057, 990, 1537)",1575,1667

In [7]:

# ============================================================
# Encode prompts and load candidate features
# ============================================================

SUPPORTED_TOKEN_MODES = {
    "all_query_tokens",
    "last_query_token",
    "assistant_generation_prefix_token",
    "last_prompt_token",
}

for mode in CAUSAL_INTERVENTION_TOKEN_MODES:
    if mode not in SUPPORTED_TOKEN_MODES:
        raise ValueError(
            f"Unknown token mode {mode!r}. Supported modes: {sorted(SUPPORTED_TOKEN_MODES)}"
        )


def token_positions_overlapping_char_span(offsets, span: Tuple[int, int]) -> List[int]:
    start, end = int(span[0]), int(span[1])
    positions = []
    for i, (a, b) in enumerate(offsets):
        a = int(a)
        b = int(b)
        if b <= a:
            continue
        if a < end and b > start:
            positions.append(int(i))
    return positions


def find_assistant_generation_prefix_span(prompt: str) -> Tuple[int, int]:
    """Return the character span of the final assistant-generation prefix.

    In the Qwen ChatML rendering, prompts end with something like
    `<|im_start|>assistant\n` because we use add_generation_prompt=True.
    We use the final occurrence so that demonstration assistant messages are ignored.
    """
    candidates = [
        "<|im_start|>assistant\n",
        "<|im_start|>assistant",
        "assistant\n",
    ]

    best = -1
    best_pat = None
    for pat in candidates:
        idx = prompt.rfind(pat)
        if idx > best:
            best = idx
            best_pat = pat

    if best < 0:
        # Defensive fallback: use a short final suffix.
        return (max(0, len(prompt) - 64), len(prompt))

    return (int(best), len(prompt))


def build_token_position_map(prompt: str, prompt_ids: List[int], offsets, query_span: Tuple[int, int]) -> Dict[str, List[int]]:
    all_query_tokens = token_positions_overlapping_char_span(offsets, query_span)
    if len(all_query_tokens) == 0:
        raise RuntimeError("No query-token positions found.")

    last_query_token = [int(all_query_tokens[-1])]
    last_prompt_token = [int(len(prompt_ids) - 1)]

    assistant_span = find_assistant_generation_prefix_span(prompt)
    assistant_prefix_positions = token_positions_overlapping_char_span(offsets, assistant_span)

    # Some fast tokenizers assign zero-length offsets to special/control tokens.
    # If offsets do not recover the assistant prefix, use the final prompt token as the
    # prediction-adjacent assistant prefix token.
    if len(assistant_prefix_positions) == 0:
        assistant_prefix_positions = last_prompt_token[:]

    return {
        "all_query_tokens": list(map(int, all_query_tokens)),
        "last_query_token": list(map(int, last_query_token)),
        "assistant_generation_prefix_token": list(map(int, assistant_prefix_positions)),
        "last_prompt_token": list(map(int, last_prompt_token)),
    }


def encode_causal_prompt_records(plan_df: pd.DataFrame) -> List[Dict[str, Any]]:
    records = []
    max_candidate_len = max(
        len(tokenizer(format_score(v), add_special_tokens=False)["input_ids"])
        for v in SCORE_CANDIDATE_VALUES
    )

    for row in tqdm(plan_df.itertuples(index=False), total=len(plan_df), desc="Encoding causal prompts"):
        enc = tokenizer(
            row.prompt,
            add_special_tokens=False,
            return_offsets_mapping=True,
        )
        prompt_ids = list(map(int, enc["input_ids"]))
        offsets = enc["offset_mapping"]
        query_span = (int(row.query_char_span_start), int(row.query_char_span_end))

        position_map = build_token_position_map(
            prompt=str(row.prompt),
            prompt_ids=prompt_ids,
            offsets=offsets,
            query_span=query_span,
        )

        for mode in CAUSAL_INTERVENTION_TOKEN_MODES:
            if len(position_map.get(mode, [])) == 0:
                raise RuntimeError(
                    f"No positions found for token mode {mode!r}, prompt_row_id={row.prompt_row_id}."
                )

        if len(prompt_ids) + max_candidate_len > int(MAX_PROMPT_TOKENS):
            raise RuntimeError(
                f"Prompt row {row.prompt_row_id} too long: {len(prompt_ids)} prompt tokens + "
                f"{max_candidate_len} candidate tokens > MAX_PROMPT_TOKENS={MAX_PROMPT_TOKENS}."
            )

        rec = row._asdict()
        rec["prompt_input_ids"] = prompt_ids
        rec["position_map"] = position_map
        rec["query_token_positions"] = position_map["all_query_tokens"]
        rec["assistant_generation_prefix_positions"] = position_map["assistant_generation_prefix_token"]
        rec["last_prompt_token_position"] = int(position_map["last_prompt_token"][-1])
        records.append(rec)

    return records


causal_encoded_records = encode_causal_prompt_records(causal_prompt_plan_df)

position_length_rows = []
for mode in CAUSAL_INTERVENTION_TOKEN_MODES:
    lengths = [len(r["position_map"].get(mode, [])) for r in causal_encoded_records]
    position_length_rows.append({
        "token_mode": mode,
        "mean_n_positions": float(np.mean(lengths)),
        "min_n_positions": int(np.min(lengths)),
        "max_n_positions": int(np.max(lengths)),
    })
print("Intervention token-position counts:")
display(pd.DataFrame(position_length_rows))

candidate_score_token_ids = []
for v in SCORE_CANDIDATE_VALUES:
    score_str = format_score(float(v))
    ids = tokenizer(score_str, add_special_tokens=False)["input_ids"]
    ids = list(map(int, ids))
    if len(ids) == 0:
        raise RuntimeError(f"Candidate score string {score_str!r} tokenized to empty list.")
    candidate_score_token_ids.append(ids)

candidate_tokenization_df = pd.DataFrame({
    "score_value": SCORE_CANDIDATE_VALUES,
    "score_string": [format_score(v) for v in SCORE_CANDIDATE_VALUES],
    "token_ids": candidate_score_token_ids,
    "n_tokens": [len(x) for x in candidate_score_token_ids],
})
print("Candidate score tokenization:")
display(candidate_tokenization_df)


def load_candidate_features() -> List[int]:
    if CANDIDATE_FEATURES is not None:
        feats = [int(x) for x in CANDIDATE_FEATURES]
        print("Using manually supplied CANDIDATE_FEATURES.")
        return feats

    path = DISCOVERY_RESULT_DIR / "stsb_feature_score_proximity_correlations_latest.csv.gz"
    if path.exists():
        print("Loading candidate features from discovery result:", path)
        df = pd.read_csv(path)
        if "feature_idx" not in df.columns:
            raise KeyError(f"No feature_idx column in discovery file: {path}")
        feats = df.head(int(N_CANDIDATE_FEATURES_FROM_DISCOVERY))["feature_idx"].astype(int).tolist()
        return feats

    if len(FALLBACK_CANDIDATE_FEATURES) == 0:
        raise FileNotFoundError(
            "Discovery feature file was not found and FALLBACK_CANDIDATE_FEATURES is empty. "
            f"Expected Qwen3-0.6B discovery results at: {path}. "
            "Run STS_B_Proximity_DPS_Qwen3-0.6B-IT.ipynb first, or manually set "
            "CANDIDATE_FEATURES to a list of Qwen3-0.6B SAE feature indices."
        )

    print("Discovery feature file not found; using FALLBACK_CANDIDATE_FEATURES.")
    return [int(x) for x in FALLBACK_CANDIDATE_FEATURES[: int(N_CANDIDATE_FEATURES_FROM_DISCOVERY)]]


CANDIDATE_DPS_STS_FEATURES = load_candidate_features()
print(f"Number of candidate features: {len(CANDIDATE_DPS_STS_FEATURES)}")
print(CANDIDATE_DPS_STS_FEATURES)

Encoding causal prompts:   0%|          | 0/960 [00:00<?, ?it/s]

Intervention token-position counts:

,token_mode,mean_n_positions,min_n_positions,max_n_positions
0,all_query_tokens,34.5875,18,85
1,last_query_token,1.0000,1,1
2,assistant_generation_prefix_token,5.0000,5,5
3,last_prompt_token,1.0000,1,1

Candidate score tokenization:

    score_value score_string     token_ids  n_tokens
0           0.0          0.0  [15, 13, 15]         3
1           0.5          0.5  [15, 13, 20]         3
2           1.0          1.0  [16, 13, 15]         3
3           1.5          1.5  [16, 13, 20]         3
4           2.0          2.0  [17, 13, 15]         3
5           2.5          2.5  [17, 13, 20]         3
6           3.0          3.0  [18, 13, 15]         3
7           3.5          3.5  [18, 13, 20]         3
8           4.0          4.0  [19, 13, 15]         3
9           4.5          4.5  [19, 13, 20]         3
10          5.0          5.0  [20, 13, 15]         3

Using manually supplied CANDIDATE_FEATURES.
Number of candidate features: 5
[4724, 6396, 3901, 6537, 4140]

In [8]:

# ============================================================
# Causal steering and numeric score prediction
# ============================================================


def make_feature_steering_hook(feature_idx: int, alpha: float, batch_token_positions: List[List[int]]):
    feature_idx = int(feature_idx)
    alpha = float(alpha)
    direction = sae.W_dec[feature_idx].detach().to(device=TARGET_LAYER_DEVICE, dtype=DTYPE)
    if NORMALIZE_STEERING_DIRECTION:
        direction = direction / (direction.norm() + 1e-8)
    direction = direction * alpha

    def hook_fn(module, inputs, output):
        if isinstance(output, tuple):
            hidden = output[0]
        else:
            hidden = output
        hidden_new = hidden.clone()
        for b, positions in enumerate(batch_token_positions):
            if len(positions) == 0:
                continue
            pos = torch.as_tensor(positions, dtype=torch.long, device=hidden_new.device)
            # Ensure no out-of-range positions after batching/padding.
            pos = pos[(pos >= 0) & (pos < hidden_new.shape[1])]
            if len(pos) == 0:
                continue
            hidden_new[b, pos, :] = hidden_new[b, pos, :] + direction.to(device=hidden_new.device, dtype=hidden_new.dtype)
        if isinstance(output, tuple):
            return (hidden_new,) + output[1:]
        return hidden_new

    return hook_fn


def _pad_batch(input_id_lists: List[List[int]], pad_token_id: int) -> Tuple[torch.Tensor, torch.Tensor]:
    max_len = max(len(x) for x in input_id_lists)
    input_ids = torch.full((len(input_id_lists), max_len), int(pad_token_id), dtype=torch.long)
    attention_mask = torch.zeros((len(input_id_lists), max_len), dtype=torch.long)
    for i, ids in enumerate(input_id_lists):
        ids_t = torch.tensor(ids, dtype=torch.long)
        input_ids[i, : len(ids)] = ids_t
        attention_mask[i, : len(ids)] = 1
    return input_ids, attention_mask


def score_expected_sts_for_records(
    records: List[Dict[str, Any]],
    *,
    feature_idx: Optional[int] = None,
    alpha: Optional[float] = None,
    token_mode: Optional[str] = None,
    batch_size: int = SCORE_BATCH_SIZE,
    cache_name: Optional[str] = None,
) -> pd.DataFrame:
    """Score each prompt by the expected value over numeric candidate strings.

    If feature_idx/alpha are provided, adds the SAE decoder direction at the
    token positions specified by token_mode.
    """
    steering_active = feature_idx is not None and alpha is not None and float(alpha) != 0.0
    if steering_active:
        if token_mode is None:
            raise ValueError("token_mode must be provided when steering is active.")
        if token_mode not in SUPPORTED_TOKEN_MODES:
            raise ValueError(f"Unknown token_mode={token_mode!r}.")

    if cache_name is not None:
        cache_path = SCORE_CACHE_DIR / f"{cache_name}.csv.gz"
        if cache_path.exists():
            cached_df = pd.read_csv(cache_path)

            # Robust stale-cache guard. The most common failure mode is changing
            # CAUSAL_N_TEST_QUERIES_TOTAL after a previous run: baseline caches then have
            # a different prompt plan size and merging silently loses rows later.
            expected_prompt_row_ids = [int(r["prompt_row_id"]) for r in records]
            cache_is_valid = (
                len(cached_df) == len(records)
                and "prompt_row_id" in cached_df.columns
                and cached_df["prompt_row_id"].astype(int).tolist() == expected_prompt_row_ids
            )

            if "cache_tag" in cached_df.columns:
                cache_is_valid = cache_is_valid and cached_df["cache_tag"].astype(str).eq(str(CAUSAL_PLAN_CACHE_TAG)).all()

            if cache_is_valid:
                print("Loading cached score predictions:", cache_path)
                return cached_df

            print(
                "Ignoring stale score-prediction cache:", cache_path,
                f"(cached rows={len(cached_df)}, expected rows={len(records)})"
            )
    else:
        cache_path = None

    pad_token_id = tokenizer.pad_token_id
    if pad_token_id is None:
        pad_token_id = tokenizer.eos_token_id

    flat_entries = []
    for rec_idx, rec in enumerate(records):
        prompt_ids = list(map(int, rec["prompt_input_ids"]))
        selected_positions = []
        if steering_active:
            selected_positions = list(map(int, rec["position_map"].get(token_mode, [])))
            if len(selected_positions) == 0:
                raise RuntimeError(
                    f"No selected positions for token_mode={token_mode!r}, prompt_row_id={rec['prompt_row_id']}"
                )
        for cand_idx, cand_ids in enumerate(candidate_score_token_ids):
            full_ids = prompt_ids + list(map(int, cand_ids))
            cand_positions = list(range(len(prompt_ids), len(prompt_ids) + len(cand_ids)))
            flat_entries.append({
                "rec_idx": int(rec_idx),
                "candidate_idx": int(cand_idx),
                "input_ids": full_ids,
                "candidate_ids": list(map(int, cand_ids)),
                "candidate_positions": cand_positions,
                "selected_token_positions": selected_positions,
            })

    logprob_matrix = np.full((len(records), len(SCORE_CANDIDATE_VALUES)), np.nan, dtype=np.float32)
    layer_module = model.get_submodule(f"model.layers.{TARGET_LAYER}")

    desc = f"Scoring feature={feature_idx}, alpha={alpha}, mode={token_mode}"
    for start in tqdm(range(0, len(flat_entries), int(batch_size)), desc=desc):
        batch = flat_entries[start : start + int(batch_size)]
        input_id_lists = [b["input_ids"] for b in batch]
        input_ids_cpu, attention_mask_cpu = _pad_batch(input_id_lists, pad_token_id=pad_token_id)
        input_ids = input_ids_cpu.to(MODEL_INPUT_DEVICE)
        attention_mask = attention_mask_cpu.to(MODEL_INPUT_DEVICE)
        batch_positions = [b["selected_token_positions"] for b in batch]

        hook_handle = None
        try:
            if steering_active:
                hook_handle = layer_module.register_forward_hook(
                    make_feature_steering_hook(
                        feature_idx=int(feature_idx),
                        alpha=float(alpha),
                        batch_token_positions=batch_positions,
                    )
                )
            with torch.no_grad():
                out = model(input_ids=input_ids, attention_mask=attention_mask)
                logits = out.logits.float()
                log_probs = F.log_softmax(logits, dim=-1)
        finally:
            if hook_handle is not None:
                hook_handle.remove()

        for bi, entry in enumerate(batch):
            lp = 0.0
            for pos, tok in zip(entry["candidate_positions"], entry["candidate_ids"]):
                # Token at `pos` is predicted by logits at `pos-1`.
                lp += float(log_probs[bi, int(pos) - 1, int(tok)].detach().cpu().item())
            if LENGTH_NORMALIZE_SCORE_LOGPROBS:
                lp = lp / max(1, len(entry["candidate_ids"]))
            logprob_matrix[int(entry["rec_idx"]), int(entry["candidate_idx"])] = float(lp)

        del input_ids, attention_mask, logits, log_probs
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # Convert candidate logprobs into a normalized distribution over candidate numeric scores.
    values = np.asarray(SCORE_CANDIDATE_VALUES, dtype=np.float32)
    rows = []
    for rec_idx, rec in enumerate(records):
        lps = logprob_matrix[rec_idx].astype(np.float64)
        lps = lps - np.nanmax(lps)
        probs = np.exp(lps)
        probs = probs / np.nansum(probs)
        pred_score = float(np.nansum(probs * values))
        best_idx = int(np.nanargmax(probs))
        rows.append({
            "prompt_row_id": int(rec["prompt_row_id"]),
            "query_global_id": int(rec["query_global_id"]),
            "query_score": float(rec["query_score"]),
            "query_score_anchor": float(rec["query_score_anchor"]),
            "first_demo_anchor": float(rec["first_demo_anchor"]),
            "first_demo_score": float(rec["first_demo_score"]),
            "score_distance": float(rec["score_distance"]),
            "score_proximity": float(rec["score_proximity"]),
            "pred_score_expected": pred_score,
            "pred_score_argmax": float(values[best_idx]),
            "candidate_logprobs_json": json.dumps({format_score(values[j]): float(logprob_matrix[rec_idx, j]) for j in range(len(values))}),
            "candidate_probs_json": json.dumps({format_score(values[j]): float(probs[j]) for j in range(len(values))}),
            "cache_tag": str(CAUSAL_PLAN_CACHE_TAG),
        })

    out_df = pd.DataFrame(rows)
    if cache_path is not None:
        out_df.to_csv(cache_path, index=False, compression="gzip")
        print("Saved score predictions:", cache_path)
    return out_df


print("Computing/loading baseline numeric score predictions...")
baseline_score_df = score_expected_sts_for_records(
    causal_encoded_records,
    feature_idx=None,
    alpha=None,
    token_mode=None,
    batch_size=SCORE_BATCH_SIZE,
    cache_name="baseline_score_predictions",
)
print("Baseline score predictions:", baseline_score_df.shape)
display(baseline_score_df.head())

Computing/loading baseline numeric score predictions...

Scoring feature=None, alpha=None, mode=None:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/baseline_score_predictions.csv.gz
Baseline score predictions: (960, 13)

,prompt_row_id,query_global_id,query_score,query_score_anchor,first_demo_anchor,first_demo_score,score_distance,score_proximity,pred_score_expected,pred_score_argmax,candidate_logprobs_json,candidate_probs_json,cache_tag
0,0,0,0.0,0.0,0.0,0.2,0.2,-0.2,2.090726,0.0,"{""0.0"": -26.05504608154297, ""0.5"": -27.5550460...","{""0.0"": 0.23877216373372392, ""0.5"": 0.05327727...",seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_...
1,1,0,0.0,0.0,1.0,0.6,0.6,-0.6,2.108512,0.0,"{""0.0"": -26.09328269958496, ""0.5"": -27.5932826...","{""0.0"": 0.23699387516653114, ""0.5"": 0.05288048...",seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_...
2,2,0,0.0,0.0,2.0,1.8,1.8,-1.8,1.788353,0.0,"{""0.0"": -25.740983963012695, ""0.5"": -28.490983...","{""0.0"": 0.3951100280047314, ""0.5"": 0.025258539...",seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_...
3,3,0,0.0,0.0,3.0,3.0,3.0,-3.0,1.899592,0.0,"{""0.0"": -25.500186920166016, ""0.5"": -28.250186...","{""0.0"": 0.32476542464100405, ""0.5"": 0.02076155...",seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_...
4,4,0,0.0,0.0,4.0,4.4,4.4,-4.4,1.770493,0.0,"{""0.0"": -24.97441291809082, ""0.5"": -27.3494129...","{""0.0"": 0.35609889887410406, ""0.5"": 0.03312235...",seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_...

In [9]:

# ============================================================
# Run causal STS first-demo-score-anchor evaluation with checkpointing
# ============================================================

# Store effect checkpoints under the same prompt-plan cache tag. This prevents
# feature/alpha/mode checkpoints computed with one prompt-plan size from being loaded
# after changing CAUSAL_N_TEST_QUERIES_TOTAL or related prompt-plan settings.
CAUSAL_EFFECT_CHECKPOINT_DIR = RESULT_DIR / "feature_alpha_tokenmode_causal_effect_checkpoints" / CAUSAL_PLAN_CACHE_TAG
CAUSAL_EFFECT_CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
FORCE_RECOMPUTE_CAUSAL_STS = False


def safe_alpha_tag(alpha: float) -> str:
    s = f"{float(alpha):.10g}"
    return s.replace("-", "m").replace("+", "").replace(".", "p")


def safe_mode_tag(token_mode: str) -> str:
    return str(token_mode).replace("/", "_").replace(" ", "_")


def feature_alpha_mode_effect_path(feature_idx: int, alpha: float, token_mode: str) -> Path:
    return (
        CAUSAL_EFFECT_CHECKPOINT_DIR
        / f"feature_{int(feature_idx)}__alpha_{safe_alpha_tag(alpha)}__mode_{safe_mode_tag(token_mode)}__effects.csv.gz"
    )


def compute_causal_effect_df_for_feature_alpha_mode(feature_idx: int, alpha: float, token_mode: str) -> pd.DataFrame:
    cache_name = (
        f"feature_{int(feature_idx)}__alpha_{safe_alpha_tag(alpha)}"
        f"__mode_{safe_mode_tag(token_mode)}__score_predictions"
    )
    steered_score_df = score_expected_sts_for_records(
        causal_encoded_records,
        feature_idx=int(feature_idx),
        alpha=float(alpha),
        token_mode=str(token_mode),
        batch_size=SCORE_BATCH_SIZE,
        cache_name=cache_name,
    )

    merged = baseline_score_df.merge(
        steered_score_df[["prompt_row_id", "pred_score_expected", "pred_score_argmax"]].rename(columns={
            "pred_score_expected": "steered_pred_score_expected",
            "pred_score_argmax": "steered_pred_score_argmax",
        }),
        on="prompt_row_id",
        how="inner",
    )
    if len(merged) != len(baseline_score_df):
        missing_from_steered = sorted(
            set(baseline_score_df["prompt_row_id"].astype(int))
            - set(steered_score_df["prompt_row_id"].astype(int))
        )[:10]
        extra_in_steered = sorted(
            set(steered_score_df["prompt_row_id"].astype(int))
            - set(baseline_score_df["prompt_row_id"].astype(int))
        )[:10]
        raise RuntimeError(
            f"Merge lost rows for feature {feature_idx}, alpha={alpha}, mode={token_mode}: "
            f"{len(merged)} vs {len(baseline_score_df)}. "
            f"This usually indicates a stale cache. "
            f"CAUSAL_PLAN_CACHE_TAG={CAUSAL_PLAN_CACHE_TAG}. "
            f"missing_from_steered_first10={missing_from_steered}; "
            f"extra_in_steered_first10={extra_in_steered}"
        )

    merged = merged.rename(columns={
        "pred_score_expected": "baseline_pred_score_expected",
        "pred_score_argmax": "baseline_pred_score_argmax",
    })

    y = merged["query_score"].astype(float)
    first_score = merged["first_demo_score"].astype(float)
    first_anchor = merged["first_demo_anchor"].astype(float)
    base = merged["baseline_pred_score_expected"].astype(float)
    steer = merged["steered_pred_score_expected"].astype(float)
    delta = steer - base

    merged["feature_idx"] = int(feature_idx)
    merged["alpha"] = float(alpha)
    merged["token_mode"] = str(token_mode)

    # Prediction shift induced by steering.
    merged["delta_pred_score_expected"] = delta
    merged["abs_delta_pred_score_expected"] = delta.abs()

    # Original score-proximity variables, retained for comparison.
    merged["baseline_squared_error"] = (base - y) ** 2
    merged["steered_squared_error"] = (steer - y) ** 2
    merged["squared_error_improvement"] = merged["baseline_squared_error"] - merged["steered_squared_error"]
    merged["baseline_abs_error"] = (base - y).abs()
    merged["steered_abs_error"] = (steer - y).abs()
    merged["absolute_error_improvement"] = merged["baseline_abs_error"] - merged["steered_abs_error"]
    merged["moved_toward_gold"] = delta * np.sign(y - base)

    # New first-demo-score-anchor causal diagnostics.
    # If this feature carries first-demo score information, adding the feature should
    # shift the model prediction in the direction of first_demo_score - baseline_prediction.
    merged["anchor_pull_vector"] = first_score - base
    merged["anchor_pull_anchor_vector"] = first_anchor - base
    merged["anchor_pull_direction"] = np.sign(merged["anchor_pull_vector"])
    merged["anchor_pull_anchor_direction"] = np.sign(merged["anchor_pull_anchor_vector"])

    # Positive values mean the score shift points toward the actual first-demo score.
    merged["signed_shift_toward_first_demo_score"] = delta * merged["anchor_pull_direction"]
    merged["signed_shift_toward_first_demo_anchor"] = delta * merged["anchor_pull_anchor_direction"]

    # Positive values mean steering reduces the distance from the model prediction to the first-demo score.
    merged["baseline_distance_to_first_demo_score"] = (base - first_score).abs()
    merged["steered_distance_to_first_demo_score"] = (steer - first_score).abs()
    merged["first_demo_score_distance_reduction"] = (
        merged["baseline_distance_to_first_demo_score"]
        - merged["steered_distance_to_first_demo_score"]
    )

    merged["baseline_distance_to_first_demo_anchor"] = (base - first_anchor).abs()
    merged["steered_distance_to_first_demo_anchor"] = (steer - first_anchor).abs()
    merged["first_demo_anchor_distance_reduction"] = (
        merged["baseline_distance_to_first_demo_anchor"]
        - merged["steered_distance_to_first_demo_anchor"]
    )

    # Dot-product-like effects: positive means shift is directionally aligned with the first-demo score.
    merged["anchor_pull_dot_score"] = delta * merged["anchor_pull_vector"]
    merged["anchor_pull_dot_anchor"] = delta * merged["anchor_pull_anchor_vector"]

    return merged


all_effect_tables = []
for token_mode in CAUSAL_INTERVENTION_TOKEN_MODES:
    print("\n" + "#" * 100)
    print("Token mode =", token_mode)
    print("#" * 100)

    for alpha in CAUSAL_ALPHA_VALUES:
        alpha = float(alpha)
        print("\n" + "=" * 100)
        print("Running STS first-demo-score-anchor causal evaluation for alpha =", alpha)
        print("=" * 100)

        for n, feature_idx in enumerate(CANDIDATE_DPS_STS_FEATURES, start=1):
            feature_idx = int(feature_idx)
            path = feature_alpha_mode_effect_path(feature_idx, alpha, token_mode)
            if path.exists() and not FORCE_RECOMPUTE_CAUSAL_STS:
                print(
                    f"[{n}/{len(CANDIDATE_DPS_STS_FEATURES)}] "
                    f"feature {feature_idx}, alpha={alpha}, mode={token_mode} -- loading checkpoint"
                )
                effect_df = pd.read_csv(path)
            else:
                print(
                    f"[{n}/{len(CANDIDATE_DPS_STS_FEATURES)}] "
                    f"feature {feature_idx}, alpha={alpha}, mode={token_mode} -- computing"
                )
                effect_df = compute_causal_effect_df_for_feature_alpha_mode(
                    feature_idx,
                    alpha,
                    token_mode,
                )
                effect_df.to_csv(path, index=False, compression="gzip")
                print("  Saved checkpoint:", path)

            all_effect_tables.append(effect_df)
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

causal_effect_df = pd.concat(all_effect_tables, ignore_index=True) if all_effect_tables else pd.DataFrame()
causal_effect_path = RESULT_DIR / "stsb_anchor_pull_causal_prompt_level_effects_latest.csv.gz"
causal_effect_df.to_csv(causal_effect_path, index=False, compression="gzip")
print("Saved prompt-level causal effects:", causal_effect_path)
print("Causal effect table:", causal_effect_df.shape)
display(causal_effect_df.head())

####################################################################################################
Token mode = all_query_tokens
####################################################################################################

====================================================================================================
Running STS first-demo-score-anchor causal evaluation for alpha = 10.0
====================================================================================================
[1/5] feature 4724, alpha=10.0, mode=all_query_tokens -- computing

Scoring feature=4724, alpha=10.0, mode=all_query_tokens:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4724__alpha_10__mode_all_query_tokens__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4724__alpha_10__mode_all_query_tokens__effects.csv.gz
[2/5] feature 6396, alpha=10.0, mode=all_query_tokens -- computing

Scoring feature=6396, alpha=10.0, mode=all_query_tokens:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6396__alpha_10__mode_all_query_tokens__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6396__alpha_10__mode_all_query_tokens__effects.csv.gz
[3/5] feature 3901, alpha=10.0, mode=all_query_tokens -- computing

Scoring feature=3901, alpha=10.0, mode=all_query_tokens:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_3901__alpha_10__mode_all_query_tokens__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_3901__alpha_10__mode_all_query_tokens__effects.csv.gz
[4/5] feature 6537, alpha=10.0, mode=all_query_tokens -- computing

Scoring feature=6537, alpha=10.0, mode=all_query_tokens:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6537__alpha_10__mode_all_query_tokens__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6537__alpha_10__mode_all_query_tokens__effects.csv.gz
[5/5] feature 4140, alpha=10.0, mode=all_query_tokens -- computing

Scoring feature=4140, alpha=10.0, mode=all_query_tokens:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4140__alpha_10__mode_all_query_tokens__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4140__alpha_10__mode_all_query_tokens__effects.csv.gz

####################################################################################################
Token mode = last_query_token
####################################################################################################

====================================================================================================
Running STS first-demo-score-anchor causal evaluation for alpha = 10.0
====================================================================================================
[1/5] feature 4724, alpha=10.0, mode=last_query_token -- computing

Scoring feature=4724, alpha=10.0, mode=last_query_token:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4724__alpha_10__mode_last_query_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4724__alpha_10__mode_last_query_token__effects.csv.gz
[2/5] feature 6396, alpha=10.0, mode=last_query_token -- computing

Scoring feature=6396, alpha=10.0, mode=last_query_token:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6396__alpha_10__mode_last_query_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6396__alpha_10__mode_last_query_token__effects.csv.gz
[3/5] feature 3901, alpha=10.0, mode=last_query_token -- computing

Scoring feature=3901, alpha=10.0, mode=last_query_token:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_3901__alpha_10__mode_last_query_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_3901__alpha_10__mode_last_query_token__effects.csv.gz
[4/5] feature 6537, alpha=10.0, mode=last_query_token -- computing

Scoring feature=6537, alpha=10.0, mode=last_query_token:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6537__alpha_10__mode_last_query_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6537__alpha_10__mode_last_query_token__effects.csv.gz
[5/5] feature 4140, alpha=10.0, mode=last_query_token -- computing

Scoring feature=4140, alpha=10.0, mode=last_query_token:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4140__alpha_10__mode_last_query_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4140__alpha_10__mode_last_query_token__effects.csv.gz

####################################################################################################
Token mode = assistant_generation_prefix_token
####################################################################################################

====================================================================================================
Running STS first-demo-score-anchor causal evaluation for alpha = 10.0
====================================================================================================
[1/5] feature 4724, alpha=10.0, mode=assistant_generation_prefix_token -- computing

Scoring feature=4724, alpha=10.0, mode=assistant_generation_prefix_token:   0%|          | 0/1320 [00:00<?, ?i…

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4724__alpha_10__mode_assistant_generation_prefix_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4724__alpha_10__mode_assistant_generation_prefix_token__effects.csv.gz
[2/5] feature 6396, alpha=10.0, mode=assistant_generation_prefix_token -- computing

Scoring feature=6396, alpha=10.0, mode=assistant_generation_prefix_token:   0%|          | 0/1320 [00:00<?, ?i…

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6396__alpha_10__mode_assistant_generation_prefix_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6396__alpha_10__mode_assistant_generation_prefix_token__effects.csv.gz
[3/5] feature 3901, alpha=10.0, mode=assistant_generation_prefix_token -- computing

Scoring feature=3901, alpha=10.0, mode=assistant_generation_prefix_token:   0%|          | 0/1320 [00:00<?, ?i…

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_3901__alpha_10__mode_assistant_generation_prefix_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_3901__alpha_10__mode_assistant_generation_prefix_token__effects.csv.gz
[4/5] feature 6537, alpha=10.0, mode=assistant_generation_prefix_token -- computing

Scoring feature=6537, alpha=10.0, mode=assistant_generation_prefix_token:   0%|          | 0/1320 [00:00<?, ?i…

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6537__alpha_10__mode_assistant_generation_prefix_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6537__alpha_10__mode_assistant_generation_prefix_token__effects.csv.gz
[5/5] feature 4140, alpha=10.0, mode=assistant_generation_prefix_token -- computing

Scoring feature=4140, alpha=10.0, mode=assistant_generation_prefix_token:   0%|          | 0/1320 [00:00<?, ?i…

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4140__alpha_10__mode_assistant_generation_prefix_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4140__alpha_10__mode_assistant_generation_prefix_token__effects.csv.gz

####################################################################################################
Token mode = last_prompt_token
####################################################################################################

====================================================================================================
Running STS first-demo-score-anchor causal evaluation for alpha = 10.0
====================================================================================================
[1/5] feature 4724, alpha=10.0, mode=last_prompt_token -- computing

Scoring feature=4724, alpha=10.0, mode=last_prompt_token:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4724__alpha_10__mode_last_prompt_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4724__alpha_10__mode_last_prompt_token__effects.csv.gz
[2/5] feature 6396, alpha=10.0, mode=last_prompt_token -- computing

Scoring feature=6396, alpha=10.0, mode=last_prompt_token:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6396__alpha_10__mode_last_prompt_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6396__alpha_10__mode_last_prompt_token__effects.csv.gz
[3/5] feature 3901, alpha=10.0, mode=last_prompt_token -- computing

Scoring feature=3901, alpha=10.0, mode=last_prompt_token:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_3901__alpha_10__mode_last_prompt_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_3901__alpha_10__mode_last_prompt_token__effects.csv.gz
[4/5] feature 6537, alpha=10.0, mode=last_prompt_token -- computing

Scoring feature=6537, alpha=10.0, mode=last_prompt_token:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6537__alpha_10__mode_last_prompt_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_6537__alpha_10__mode_last_prompt_token__effects.csv.gz
[5/5] feature 4140, alpha=10.0, mode=last_prompt_token -- computing

Scoring feature=4140, alpha=10.0, mode=last_prompt_token:   0%|          | 0/1320 [00:00<?, ?it/s]

Saved score predictions: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/score_prediction_cache/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4140__alpha_10__mode_last_prompt_token__score_predictions.csv.gz
  Saved checkpoint: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/feature_alpha_tokenmode_causal_effect_checkpoints/seed42__nq160__demos6__q0_1_2_3_4_5__v0_1_2_3_4_5__nv1__step0p5/feature_4140__alpha_10__mode_last_prompt_token__effects.csv.gz
Saved prompt-level causal effects: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/stsb_anchor_pull_causal_prompt_level_effects_latest.csv.gz
Causal effect table: (19200, 41)

,prompt_row_id,query_global_id,query_score,query_score_anchor,first_demo_anchor,first_demo_score,score_distance,score_proximity,baseline_pred_score_expected,baseline_pred_score_argmax,...,signed_shift_toward_first_demo_score,signed_shift_toward_first_demo_anchor,baseline_distance_to_first_demo_score,steered_distance_to_first_demo_score,first_demo_score_distance_reduction,baseline_distance_to_first_demo_anchor,steered_distance_to_first_demo_anchor,first_demo_anchor_distance_reduction,anchor_pull_dot_score,anchor_pull_dot_anchor
0,0,0,0.0,0.0,0.0,0.2,0.2,-0.2,2.090726,0.0,...,-0.037221,-0.037221,1.890726,1.927946,-0.037221,2.090726,2.127946,-0.037221,-0.070374,-0.077818
1,1,0,0.0,0.0,1.0,0.6,0.6,-0.6,2.108512,0.0,...,0.113454,0.113454,1.508512,1.395058,0.113454,1.108512,0.995058,0.113454,0.171147,0.125766
2,2,0,0.0,0.0,2.0,1.8,1.8,-1.8,1.788353,0.0,...,0.074879,0.074879,0.011647,0.063232,-0.051585,0.211647,0.136768,0.074879,0.000872,0.015848
3,3,0,0.0,0.0,3.0,3.0,3.0,-3.0,1.899592,0.0,...,-0.077844,-0.077844,1.100408,1.178252,-0.077844,1.100408,1.178252,-0.077844,-0.085661,-0.085661
4,4,0,0.0,0.0,4.0,4.4,4.4,-4.4,1.770493,0.0,...,-0.264118,-0.264118,2.629507,2.893625,-0.264118,2.229507,2.493625,-0.264118,-0.694501,-0.588854

### Anchor-pull analysis distance filter

The main anchor-pull causal summaries below ignore near-anchor cases where `|first_demo_score - baseline_expected_score| < 1.0`. These cases are intrinsically noisy because the model's baseline expected score is already close to the first-demo score, so small score-estimation errors can dominate the direction of the effect. The distance-reduction plot therefore uses bins `[1,1.5)`, `[1.5,2)`, `[2,2.5)`, `[2.5,3)`, `[3,3.5)`, etc.

In [10]:

# ============================================================
# Summarize first-demo-score-anchor causal effects feature-by-feature
# ============================================================

PRIMARY_ANCHOR_PULL_CORR_X = "delta_pred_score_expected"
PRIMARY_ANCHOR_PULL_CORR_Y = "anchor_pull_vector"
PRIMARY_DISTANCE_REDUCTION_COL = "first_demo_score_distance_reduction"
DISTANCE_FOR_ANCHOR_PULL_FILTER_COL = "baseline_distance_to_first_demo_score"


def pearson_1d(x: np.ndarray, y: np.ndarray, eps: float = 1e-12) -> float:
    x = np.asarray(x, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)
    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]
    y = y[mask]
    if len(x) < 3:
        return np.nan
    x = x - x.mean()
    y = y - y.mean()
    denom = math.sqrt(float((x * x).sum()) * float((y * y).sum()))
    if denom <= eps:
        return np.nan
    return float((x * y).sum() / denom)


def anchor_pull_analysis_subset(df: pd.DataFrame) -> pd.DataFrame:
    """Main analysis subset: ignore near-anchor cases where distance is too small/noisy."""
    return df[
        pd.to_numeric(df[DISTANCE_FOR_ANCHOR_PULL_FILTER_COL], errors="coerce")
        >= float(ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS)
    ].copy()


def compute_feature_anchor_pull_summary(effect_df: pd.DataFrame) -> pd.DataFrame:
    rows = []

    group_cols = ["feature_idx", "alpha", "token_mode"]
    for (feature_idx, alpha, token_mode), sub_f_full in tqdm(effect_df.groupby(group_cols), desc="Summarizing features"):
        # Main summaries intentionally exclude near-anchor cases.
        sub_f = anchor_pull_analysis_subset(sub_f_full)

        anchor_pull_corrs = []
        anchor_distance_reduction_by_query = []
        anchor_direction_success_by_query = []
        proximity_corrs_error_improvement = []
        n_filtered_conditions_by_query = []

        for qid, sub_q_full in sub_f_full.groupby("query_global_id"):
            sub_q = anchor_pull_analysis_subset(sub_q_full)
            n_filtered_conditions_by_query.append(int(len(sub_q)))
            if len(sub_q) < 3:
                continue

            # Main method B statistic, computed only on sufficiently separated anchors:
            # Does the steering-induced score shift correlate with the direction from
            # baseline score to first-demo score as we vary the first demo for a fixed query?
            corr_anchor = pearson_1d(
                sub_q["delta_pred_score_expected"].to_numpy(),
                sub_q["anchor_pull_vector"].to_numpy(),
            )
            if np.isfinite(corr_anchor):
                anchor_pull_corrs.append(corr_anchor)

            vals = sub_q[PRIMARY_DISTANCE_REDUCTION_COL].to_numpy(dtype=float)
            if len(vals) > 0 and np.isfinite(vals).any():
                anchor_distance_reduction_by_query.append(float(np.nanmean(vals)))

            directional_vals = sub_q["signed_shift_toward_first_demo_score"].to_numpy(dtype=float)
            if len(directional_vals) > 0 and np.isfinite(directional_vals).any():
                anchor_direction_success_by_query.append(float(np.nanmean(directional_vals > 0)))

            # Retain old score-proximity causal diagnostic as a secondary comparison,
            # also on the filtered anchor-pull subset for consistency.
            corr_prox = pearson_1d(
                sub_q["squared_error_improvement"].to_numpy(),
                sub_q["score_proximity"].to_numpy(),
            )
            if np.isfinite(corr_prox):
                proximity_corrs_error_improvement.append(corr_prox)

        anchor_pull_corrs = np.asarray(anchor_pull_corrs, dtype=float)
        anchor_distance_reduction_by_query = np.asarray(anchor_distance_reduction_by_query, dtype=float)
        anchor_direction_success_by_query = np.asarray(anchor_direction_success_by_query, dtype=float)
        proximity_corrs_error_improvement = np.asarray(proximity_corrs_error_improvement, dtype=float)
        n_filtered_conditions_by_query = np.asarray(n_filtered_conditions_by_query, dtype=int)

        global_anchor_pull_corr = pearson_1d(
            sub_f["delta_pred_score_expected"].to_numpy(),
            sub_f["anchor_pull_vector"].to_numpy(),
        ) if len(sub_f) else np.nan

        global_anchor_anchor_pull_corr = pearson_1d(
            sub_f["delta_pred_score_expected"].to_numpy(),
            sub_f["anchor_pull_anchor_vector"].to_numpy(),
        ) if len(sub_f) else np.nan

        global_score_proximity_corr = pearson_1d(
            sub_f["squared_error_improvement"].to_numpy(),
            sub_f["score_proximity"].to_numpy(),
        ) if len(sub_f) else np.nan

        near_mask = (
            sub_f[DISTANCE_FOR_ANCHOR_PULL_FILTER_COL].ge(float(ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS))
            & sub_f[DISTANCE_FOR_ANCHOR_PULL_FILTER_COL].lt(1.5)
        )
        far_mask = sub_f[DISTANCE_FOR_ANCHOR_PULL_FILTER_COL].ge(3.0)
        near_all = sub_f[near_mask][PRIMARY_DISTANCE_REDUCTION_COL].to_numpy(dtype=float)
        far_all = sub_f[far_mask][PRIMARY_DISTANCE_REDUCTION_COL].to_numpy(dtype=float)

        row = {
            "feature_idx": int(feature_idx),
            "alpha": float(alpha),
            "token_mode": str(token_mode),
            "anchor_pull_min_distance_for_analysis": float(ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS),
            "n_total_prompts_all_distances": int(len(sub_f_full)),
            "n_anchor_pull_analysis_prompts": int(len(sub_f)),
            "frac_prompts_kept_by_anchor_pull_filter": float(len(sub_f) / len(sub_f_full)) if len(sub_f_full) else np.nan,
            "mean_filtered_conditions_per_query": float(np.mean(n_filtered_conditions_by_query)) if len(n_filtered_conditions_by_query) else np.nan,

            # Main method B outputs on |first-demo score - baseline expected score| >= threshold.
            "mean_within_query_anchor_pull_corr": float(np.nanmean(anchor_pull_corrs)) if len(anchor_pull_corrs) else np.nan,
            "sem_within_query_anchor_pull_corr": float(np.nanstd(anchor_pull_corrs, ddof=1) / math.sqrt(len(anchor_pull_corrs))) if len(anchor_pull_corrs) > 1 else 0.0,
            "frac_query_anchor_pull_corr_positive": float(np.mean(anchor_pull_corrs > 0)) if len(anchor_pull_corrs) else np.nan,
            "frac_query_anchor_pull_corr_gt_0p25": float(np.mean(anchor_pull_corrs > 0.25)) if len(anchor_pull_corrs) else np.nan,
            "n_valid_queries_anchor_pull_corr": int(len(anchor_pull_corrs)),
            "global_anchor_pull_corr": float(global_anchor_pull_corr),
            "global_anchor_anchor_pull_corr": float(global_anchor_anchor_pull_corr),

            # Distance-reduction version of method B, also on the filtered subset.
            "mean_first_demo_score_distance_reduction": float(sub_f[PRIMARY_DISTANCE_REDUCTION_COL].mean()) if len(sub_f) else np.nan,
            "sem_first_demo_score_distance_reduction": float(sub_f[PRIMARY_DISTANCE_REDUCTION_COL].std(ddof=1) / math.sqrt(len(sub_f))) if len(sub_f) > 1 else 0.0,
            "mean_query_first_demo_score_distance_reduction": float(np.nanmean(anchor_distance_reduction_by_query)) if len(anchor_distance_reduction_by_query) else np.nan,
            "sem_query_first_demo_score_distance_reduction": float(np.nanstd(anchor_distance_reduction_by_query, ddof=1) / math.sqrt(len(anchor_distance_reduction_by_query))) if len(anchor_distance_reduction_by_query) > 1 else 0.0,
            "frac_prompts_first_demo_distance_reduction_positive": float(np.mean(sub_f[PRIMARY_DISTANCE_REDUCTION_COL] > 0)) if len(sub_f) else np.nan,
            "mean_query_frac_prompts_shift_toward_first_demo": float(np.nanmean(anchor_direction_success_by_query)) if len(anchor_direction_success_by_query) else np.nan,

            # Shift magnitude and direction on the filtered subset.
            "mean_delta_pred_score_expected": float(sub_f["delta_pred_score_expected"].mean()) if len(sub_f) else np.nan,
            "mean_abs_delta_pred_score_expected": float(sub_f["abs_delta_pred_score_expected"].mean()) if len(sub_f) else np.nan,
            "mean_signed_shift_toward_first_demo_score": float(sub_f["signed_shift_toward_first_demo_score"].mean()) if len(sub_f) else np.nan,
            "mean_anchor_pull_dot_score": float(sub_f["anchor_pull_dot_score"].mean()) if len(sub_f) else np.nan,

            # Retain score-proximity/squared-error metrics for comparison.
            "mean_within_query_error_improvement_proximity_corr": float(np.nanmean(proximity_corrs_error_improvement)) if len(proximity_corrs_error_improvement) else np.nan,
            "sem_within_query_error_improvement_proximity_corr": float(np.nanstd(proximity_corrs_error_improvement, ddof=1) / math.sqrt(len(proximity_corrs_error_improvement))) if len(proximity_corrs_error_improvement) > 1 else 0.0,
            "global_error_improvement_proximity_corr": float(global_score_proximity_corr),
            "mean_squared_error_improvement": float(sub_f["squared_error_improvement"].mean()) if len(sub_f) else np.nan,
            "mean_absolute_error_improvement": float(sub_f["absolute_error_improvement"].mean()) if len(sub_f) else np.nan,

            # Explicit near/far summaries under the new filtered definition.
            "near_1_to_1p5_mean_distance_reduction": float(np.mean(near_all)) if len(near_all) else np.nan,
            "far_ge_3_mean_distance_reduction": float(np.mean(far_all)) if len(far_all) else np.nan,
            "near_1_to_1p5_minus_far_ge_3_distance_reduction": float(np.mean(near_all) - np.mean(far_all)) if len(near_all) and len(far_all) else np.nan,
        }
        rows.append(row)

    out = pd.DataFrame(rows)
    return out.sort_values(
        [
            "mean_within_query_anchor_pull_corr",
            "mean_first_demo_score_distance_reduction",
            "mean_abs_delta_pred_score_expected",
        ],
        ascending=[False, False, False],
    ).reset_index(drop=True)


causal_summary_df = compute_feature_anchor_pull_summary(causal_effect_df)
causal_summary_path = RESULT_DIR / f"stsb_anchor_pull_causal_feature_summary_min_distance_{str(ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS).replace('.', 'p')}_latest.csv"
causal_summary_df.to_csv(causal_summary_path, index=False)
print("Saved causal summary:", causal_summary_path)
print(
    "Main anchor-pull summaries now use only prompts with "
    f"|first-demo score - baseline expected score| >= {ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS}."
)
display(causal_summary_df.head(TOP_K_FEATURES_TO_DISPLAY))

print("Best feature per token mode:")
display(
    causal_summary_df
    .sort_values("mean_within_query_anchor_pull_corr", ascending=False)
    .groupby("token_mode", as_index=False)
    .head(5)
    .sort_values(["token_mode", "mean_within_query_anchor_pull_corr"], ascending=[True, False])
)

Summarizing features:   0%|          | 0/20 [00:00<?, ?it/s]

Saved causal summary: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/stsb_anchor_pull_causal_feature_summary_min_distance_1p0_latest.csv
Main anchor-pull summaries now use only prompts with |first-demo score - baseline expected score| >= 1.0.

,feature_idx,alpha,token_mode,anchor_pull_min_distance_for_analysis,n_total_prompts_all_distances,n_anchor_pull_analysis_prompts,frac_prompts_kept_by_anchor_pull_filter,mean_filtered_conditions_per_query,mean_within_query_anchor_pull_corr,sem_within_query_anchor_pull_corr,...,mean_signed_shift_toward_first_demo_score,mean_anchor_pull_dot_score,mean_within_query_error_improvement_proximity_corr,sem_within_query_error_improvement_proximity_corr,global_error_improvement_proximity_corr,mean_squared_error_improvement,mean_absolute_error_improvement,near_1_to_1p5_mean_distance_reduction,far_ge_3_mean_distance_reduction,near_1_to_1p5_minus_far_ge_3_distance_reduction
0,6396,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.435020,0.042698,...,-0.042410,-0.196118,0.231434,0.047851,0.013651,-1.797096,-0.329863,-0.065019,-1.091914,1.026895
1,6396,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.413592,0.041673,...,-0.036421,-0.160483,0.250180,0.047644,0.027904,-1.261016,-0.236212,-0.025963,-0.886099,0.860136
2,4724,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.359493,0.041141,...,0.017429,0.016648,0.241601,0.045233,0.151355,-0.260603,-0.047031,0.020144,-0.085251,0.105395
3,3901,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.212832,0.046210,...,-0.069870,-0.225700,0.134004,0.048882,-0.009957,-0.973005,-0.183934,-0.005218,-0.708914,0.703696
4,3901,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.176470,0.048678,...,-0.089602,-0.279053,0.101318,0.049596,-0.022448,-1.158115,-0.218700,-0.019667,-0.853784,0.834118
5,4140,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.172157,0.049497,...,0.119757,0.336803,0.139485,0.047426,0.094702,-0.156137,-0.050313,0.030466,0.917568,-0.887102
6,4724,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.169345,0.046246,...,-0.016632,-0.056604,0.121021,0.050201,0.058257,-0.376192,-0.071983,-0.002364,-0.191295,0.188930
7,4140,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.168693,0.048877,...,0.120716,0.351792,0.143063,0.048518,0.086242,-0.169601,-0.049820,0.008528,1.002839,-0.994311
8,3901,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.123993,0.044548,...,0.006695,0.017243,0.097761,0.047197,0.075291,-0.009613,-0.003616,-0.003365,0.044721,-0.048086
9,3901,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.087054,0.045429,...,0.009261,0.022960,0.064548,0.045160,0.102425,-0.011376,-0.004338,0.002670,0.046873,-0.044202
10,4140,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.083609,0.045295,...,0.009185,0.019425,0.081260,0.046698,0.082531,-0.005445,-0.000784,0.010719,0.029369,-0.018650
11,6537,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.060428,0.047248,...,0.003908,0.009498,0.037818,0.048922,0.006621,-0.013056,-0.003669,0.004081,0.047912,-0.043831
12,6396,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.047286,0.047284,...,0.006819,0.014003,0.081211,0.046210,0.090157,-0.012299,-0.001456,0.008156,0.061353,-0.053196
13,6537,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.031291,0.047390,...,0.000657,0.007303,0.042123,0.046996,0.037702,-0.019133,-0.005574,-0.005994,0.050322,-0.056316
14,4140,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.029619,0.045587,...,0.002990,0.009204,0.029808,0.046411,0.037965,-0.016665,-0.003121,-0.000180,0.040008,-0.040188
15,4724,10.0,last_query_token,1.0,960,653,0.680208,4.08125,-0.013039,0.046983,...,0.002604,0.005621,0.015091,0.047315,0.012215,0.000081,-0.001053,0.006655,0.013920,-0.007266
16,6396,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,-0.034328,0.046253,...,-0.003536,-0.008186,-0.007894,0.045046,-0.016948,-0.007720,0.001466,0.000998,0.034504,-0.033506
17,6537,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,-0.074644,0.051028,...,-0.083490,-0.244423,-0.020258,0.049908,-0.050883,-0.951670,-0.173707,0.015008,-0.712315,0.727323
18,4724,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,-0.118978,0.044475,...,-0.012750,-0.021376,-0.092592,0.045746,-0.077927,-0.005049,0.000323,-0.015566,0.024048,-0.039614
19,6537,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,-0.153004,0.049781,...,-0.111459,-0.317118,-0.073422,0.051405,-0.065149,-1.203688,-0.215259,-0.003014,-0.878062,0.875048

Best feature per token mode:

,feature_idx,alpha,token_mode,anchor_pull_min_distance_for_analysis,n_total_prompts_all_distances,n_anchor_pull_analysis_prompts,frac_prompts_kept_by_anchor_pull_filter,mean_filtered_conditions_per_query,mean_within_query_anchor_pull_corr,sem_within_query_anchor_pull_corr,...,mean_signed_shift_toward_first_demo_score,mean_anchor_pull_dot_score,mean_within_query_error_improvement_proximity_corr,sem_within_query_error_improvement_proximity_corr,global_error_improvement_proximity_corr,mean_squared_error_improvement,mean_absolute_error_improvement,near_1_to_1p5_mean_distance_reduction,far_ge_3_mean_distance_reduction,near_1_to_1p5_minus_far_ge_3_distance_reduction
9,3901,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.087054,0.045429,...,0.009261,0.022960,0.064548,0.045160,0.102425,-0.011376,-0.004338,0.002670,0.046873,-0.044202
13,6537,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.031291,0.047390,...,0.000657,0.007303,0.042123,0.046996,0.037702,-0.019133,-0.005574,-0.005994,0.050322,-0.056316
14,4140,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.029619,0.045587,...,0.002990,0.009204,0.029808,0.046411,0.037965,-0.016665,-0.003121,-0.000180,0.040008,-0.040188
16,6396,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,-0.034328,0.046253,...,-0.003536,-0.008186,-0.007894,0.045046,-0.016948,-0.007720,0.001466,0.000998,0.034504,-0.033506
18,4724,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,-0.118978,0.044475,...,-0.012750,-0.021376,-0.092592,0.045746,-0.077927,-0.005049,0.000323,-0.015566,0.024048,-0.039614
1,6396,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.413592,0.041673,...,-0.036421,-0.160483,0.250180,0.047644,0.027904,-1.261016,-0.236212,-0.025963,-0.886099,0.860136
4,3901,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.176470,0.048678,...,-0.089602,-0.279053,0.101318,0.049596,-0.022448,-1.158115,-0.218700,-0.019667,-0.853784,0.834118
6,4724,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.169345,0.046246,...,-0.016632,-0.056604,0.121021,0.050201,0.058257,-0.376192,-0.071983,-0.002364,-0.191295,0.188930
7,4140,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.168693,0.048877,...,0.120716,0.351792,0.143063,0.048518,0.086242,-0.169601,-0.049820,0.008528,1.002839,-0.994311
17,6537,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,-0.074644,0.051028,...,-0.083490,-0.244423,-0.020258,0.049908,-0.050883,-0.951670,-0.173707,0.015008,-0.712315,0.727323
0,6396,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.435020,0.042698,...,-0.042410,-0.196118,0.231434,0.047851,0.013651,-1.797096,-0.329863,-0.065019,-1.091914,1.026895
2,4724,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.359493,0.041141,...,0.017429,0.016648,0.241601,0.045233,0.151355,-0.260603,-0.047031,0.020144,-0.085251,0.105395
3,3901,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.212832,0.046210,...,-0.069870,-0.225700,0.134004,0.048882,-0.009957,-0.973005,-0.183934,-0.005218,-0.708914,0.703696
5,4140,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.172157,0.049497,...,0.119757,0.336803,0.139485,0.047426,0.094702,-0.156137,-0.050313,0.030466,0.917568,-0.887102
19,6537,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,-0.153004,0.049781,...,-0.111459,-0.317118,-0.073422,0.051405,-0.065149,-1.203688,-0.215259,-0.003014,-0.878062,0.875048
8,3901,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.123993,0.044548,...,0.006695,0.017243,0.097761,0.047197,0.075291,-0.009613,-0.003616,-0.003365,0.044721,-0.048086
10,4140,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.083609,0.045295,...,0.009185,0.019425,0.081260,0.046698,0.082531,-0.005445,-0.000784,0.010719,0.029369,-0.018650
11,6537,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.060428,0.047248,...,0.003908,0.009498,0.037818,0.048922,0.006621,-0.013056,-0.003669,0.004081,0.047912,-0.043831
12,6396,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.047286,0.047284,...,0.006819,0.014003,0.081211,0.046210,0.090157,-0.012299,-0.001456,0.008156,0.061353,-0.053196
15,4724,10.0,last_query_token,1.0,960,653,0.680208,4.08125,-0.013039,0.046983,...,0.002604,0.005621,0.015091,0.047315,0.012215,0.000081,-0.001053,0.006655,0.013920,-0.007266

In [46]:

# ============================================================
# Anchor-pull causal visualizations
# ============================================================

PLOT_FONT = "Times New Roman, Times, serif"


def axis_title(text: str, size: int = 20):
    return dict(text=text, font=dict(size=size, family=PLOT_FONT))


def save_plotly_png_if_possible(fig, path: Path, width: int, height: int, scale: int = 4):
    path = Path(path)
    try:
        fig.write_image(str(path), width=width, height=height, scale=scale)
        print("Saved PNG:", path)
    except Exception as e:
        print("Could not save PNG via kaleido; interactive figure still shown. Error:", repr(e))


def best_summary_row(token_mode: Optional[str] = None):
    sub = causal_summary_df.copy()
    if token_mode is not None:
        sub = sub[sub["token_mode"].eq(str(token_mode))]
    if sub.empty:
        raise ValueError(f"No causal summary rows found for token_mode={token_mode!r}.")
    return sub.sort_values("mean_within_query_anchor_pull_corr", ascending=False).iloc[0]


def _filter_anchor_distance_for_plot(df: pd.DataFrame) -> pd.DataFrame:
    return df[
        pd.to_numeric(df["baseline_distance_to_first_demo_score"], errors="coerce")
        >= float(ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS)
    ].copy()


def plot_top_anchor_pull_features(top_k: int = 20, token_mode: Optional[str] = None):
    sub = causal_summary_df.copy()
    title_suffix = (
        f"all token modes; |first-demo − baseline| ≥ {ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS:g}"
    )
    if token_mode is not None:
        sub = sub[sub["token_mode"].eq(str(token_mode))].copy()
        title_suffix = f"{token_mode}; |first-demo − baseline| ≥ {ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS:g}"
    sub = sub.sort_values("mean_within_query_anchor_pull_corr", ascending=False).head(int(top_k)).copy()
    sub["feature_mode"] = sub["feature_idx"].astype(str) + "<br>" + sub["token_mode"].astype(str)

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=sub["feature_mode"],
        y=sub["mean_within_query_anchor_pull_corr"],
        error_y=dict(type="data", array=sub["sem_within_query_anchor_pull_corr"], visible=True, width=3),
        text=[f"{v:.3f}" for v in sub["mean_within_query_anchor_pull_corr"]],
        textposition="outside",
    ))
    fig.update_layout(
        title=dict(
            text=f"Top-{top_k} first-demo score-anchor causal features<br><sup>{title_suffix}</sup>",
            x=0.0,
            xanchor="left",
            font=dict(size=26, family=PLOT_FONT),
        ),
        xaxis=dict(title=axis_title("SAE feature / token mode", 18), tickangle=-45, tickfont=dict(size=11, family=PLOT_FONT)),
        yaxis=dict(title=axis_title("Mean within-query corr(score shift, first-demo pull)", 18), tickfont=dict(size=15, family=PLOT_FONT), zeroline=True),
        width=1200,
        height=620,
#         template="plotly_white",
        font=dict(family=PLOT_FONT, size=14),
        showlegend=False,
    )
    fig.show(config={"toImageButtonOptions": {"format": "png", "filename": "stsb_top_anchor_pull_causal_features_min_distance", "width": 1200, "height": 620, "scale": 4}})
    save_plotly_png_if_possible(fig, RESULT_DIR / "stsb_top_anchor_pull_causal_features_min_distance.png", 1200, 620)
    return fig


def plot_token_mode_comparison(top_k_features: int = 10):
    # Choose top features by their best token-mode score under the filtered analysis.
    best_per_feature = (
        causal_summary_df
        .sort_values("mean_within_query_anchor_pull_corr", ascending=False)
        .groupby("feature_idx", as_index=False)
        .head(1)
        .head(int(top_k_features))
    )
    feature_order = best_per_feature["feature_idx"].astype(int).tolist()
    sub = causal_summary_df[causal_summary_df["feature_idx"].astype(int).isin(feature_order)].copy()
    matrix = (
        sub
        .pivot_table(
            index="feature_idx",
            columns="token_mode",
            values="mean_within_query_anchor_pull_corr",
            aggfunc="mean",
        )
        .reindex(index=feature_order, columns=CAUSAL_INTERVENTION_TOKEN_MODES)
    )
    z = matrix.to_numpy(dtype=float)
    text = np.where(np.isnan(z), "", np.char.mod("%.3f", z))
    fig = go.Figure(data=go.Heatmap(
        z=z,
        x=CAUSAL_INTERVENTION_TOKEN_MODES,
        y=[str(f) for f in feature_order],
        text=text,
        texttemplate="%{text}",
        colorscale="RdBu",
        zmid=0.0,
        colorbar=dict(title=dict(text="Anchor-pull r")),
        hovertemplate="Feature: %{y}<br>Token mode: %{x}<br>Mean r: %{z:.5f}<extra></extra>",
    ))
    fig.update_layout(
        title=dict(
            text=(
                "First-demo score-anchor causal effect by feature and token mode"
                f"<br><sup>|first-demo score − baseline expected score| ≥ {ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS:g}</sup>"
            ),
            x=0.0,
            xanchor="left",
            font=dict(size=25, family=PLOT_FONT),
        ),
        xaxis=dict(title=axis_title("Steered token span", 18), tickangle=-35, tickfont=dict(size=13, family=PLOT_FONT)),
        yaxis=dict(title=axis_title("SAE feature index", 18), tickfont=dict(size=14, family=PLOT_FONT)),
        width=920,
        height=720,
#         template="plotly_white",
        font=dict(family=PLOT_FONT, size=14),
    )
    fig.show(config={"toImageButtonOptions": {"format": "png", "filename": "stsb_anchor_pull_token_mode_heatmap_min_distance", "width": 920, "height": 720, "scale": 4}})
    save_plotly_png_if_possible(fig, RESULT_DIR / "stsb_anchor_pull_token_mode_heatmap_min_distance.png", 920, 720)
    return fig


def _subset_effect(feature_idx: Optional[int] = None, alpha: Optional[float] = None, token_mode: Optional[str] = None):
    if feature_idx is None or alpha is None or token_mode is None:
        row = best_summary_row(token_mode=token_mode)
        feature_idx = int(row["feature_idx"])
        alpha = float(row["alpha"])
        token_mode = str(row["token_mode"])
    sub = causal_effect_df[
        causal_effect_df["feature_idx"].astype(int).eq(int(feature_idx))
        & np.isclose(causal_effect_df["alpha"].astype(float), float(alpha))
        & causal_effect_df["token_mode"].astype(str).eq(str(token_mode))
    ].copy()
    return sub, int(feature_idx), float(alpha), str(token_mode)


def plot_score_shift_vs_anchor_pull(feature_idx: Optional[int] = None, alpha: Optional[float] = None, token_mode: Optional[str] = None):
    sub, feature_idx, alpha, token_mode = _subset_effect(feature_idx, alpha, token_mode)
    sub = _filter_anchor_distance_for_plot(sub)
    row = causal_summary_df[
        causal_summary_df["feature_idx"].astype(int).eq(int(feature_idx))
        & np.isclose(causal_summary_df["alpha"].astype(float), float(alpha))
        & causal_summary_df["token_mode"].astype(str).eq(str(token_mode))
    ].iloc[0]

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=sub["anchor_pull_vector"],
        y=sub["delta_pred_score_expected"],
        mode="markers",
        marker=dict(size=5, opacity=0.45),
        text=[
            f"gold={g:.2f}, first={s:.2f}, base={b:.2f}"
            for g, s, b in zip(sub["query_score"], sub["first_demo_score"], sub["baseline_pred_score_expected"])
        ],
        hovertemplate="first - baseline=%{x:.3f}<br>score shift=%{y:.3f}<br>%{text}<extra></extra>",
    ))
    fig.add_hline(y=0, line_width=1)
    fig.add_vline(x=0, line_width=1)
    fig.update_layout(
        title=dict(
            text=(
                f"Feature {feature_idx}: score shift vs. first-demo pull (α={alpha:g})"
                f"<br><sup>{token_mode}; |pull| ≥ {ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS:g}; "
                f"mean within-query r={row['mean_within_query_anchor_pull_corr']:.3f}</sup>"
            ),
            x=0.0,
            xanchor="left",
            font=dict(size=24, family=PLOT_FONT),
        ),
        xaxis=dict(title=axis_title("First-demo score − baseline expected score", 18), tickfont=dict(size=15, family=PLOT_FONT)),
        yaxis=dict(title=axis_title("Steered expected score − baseline expected score", 18), tickfont=dict(size=15, family=PLOT_FONT)),
        width=820,
        height=660,
#         template="plotly_white",
        font=dict(family=PLOT_FONT, size=14),
    )
    fig.show(config={"toImageButtonOptions": {"format": "png", "filename": f"stsb_anchor_pull_feature_{feature_idx}_shift_vs_pull_min_distance", "width": 820, "height": 660, "scale": 4}})
    save_plotly_png_if_possible(fig, RESULT_DIR / f"stsb_anchor_pull_feature_{feature_idx}_shift_vs_pull_min_distance.png", 820, 660)
    return fig


def plot_distance_reduction_vs_baseline_distance(feature_idx: Optional[int] = None, alpha: Optional[float] = None, token_mode: Optional[str] = None):
    sub, feature_idx, alpha, token_mode = _subset_effect(feature_idx, alpha, token_mode)
    sub = _filter_anchor_distance_for_plot(sub)
    sub["distance_bin"] = pd.cut(
        sub["baseline_distance_to_first_demo_score"],
        bins=ANCHOR_PULL_DISTANCE_BIN_EDGES,
        labels=ANCHOR_PULL_DISTANCE_BIN_LABELS,
        right=False,
        include_lowest=True,
    )
    summary = sub.groupby("distance_bin", observed=True).agg(
        mean_reduction=("first_demo_score_distance_reduction", "mean"),
        sem_reduction=("first_demo_score_distance_reduction", lambda x: float(np.std(x, ddof=1) / np.sqrt(len(x))) if len(x) > 1 else 0.0),
        n=("first_demo_score_distance_reduction", "count"),
    ).reset_index()

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=summary["distance_bin"].astype(str),
        y=summary["mean_reduction"],
        error_y=dict(type="data", array=summary["sem_reduction"], visible=True, width=4),
        text=[f"{v:.4f}" for v in summary["mean_reduction"]],
        textposition="outside",
    ))
    fig.update_layout(
        title=dict(
            text=(
                f"Feature {feature_idx}: distance-to-first-demo reduction (α={alpha:g})"
#                 f"<br><sup>{token_mode}; only |first-demo − baseline| ≥ {ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS:g}</sup>"
            ),
            x=0.0,
            xanchor="left",
            font=dict(size=24, family=PLOT_FONT),
        ),
        xaxis=dict(title=axis_title("|first-demo score − baseline expected score|", 18), tickfont=dict(size=15, family=PLOT_FONT)),
        yaxis=dict(title=axis_title("Reduction in distance to first-demo score", 18), tickfont=dict(size=15, family=PLOT_FONT), zeroline=True),
        width=920,
        height=560,
#         template="plotly_white",
        font=dict(family=PLOT_FONT, size=14),
        showlegend=False,
    )
    fig.show(config={"toImageButtonOptions": {"format": "png", "filename": f"stsb_anchor_pull_feature_{feature_idx}_distance_reduction_min_distance", "width": 920, "height": 560, "scale": 4}})
    save_plotly_png_if_possible(fig, RESULT_DIR / f"stsb_anchor_pull_feature_{feature_idx}_distance_reduction_min_distance.png", 920, 560)
    display(summary)
    return fig


def plot_score_shift_grid(feature_idx: Optional[int] = None, alpha: Optional[float] = None, token_mode: Optional[str] = None):
    sub, feature_idx, alpha, token_mode = _subset_effect(feature_idx, alpha, token_mode)
    sub = _filter_anchor_distance_for_plot(sub)
    grid = sub.groupby(["query_score_anchor", "first_demo_anchor"], as_index=False).agg(
        mean_score_shift=("delta_pred_score_expected", "mean"),
        mean_distance_reduction=("first_demo_score_distance_reduction", "mean"),
        n=("delta_pred_score_expected", "count"),
    )
    anchors_y = list(map(float, QUERY_SCORE_ANCHORS))
    anchors_x = list(map(float, VARIABLE_DEMO_SCORE_ANCHORS))
    z = np.full((len(anchors_y), len(anchors_x)), np.nan, dtype=float)
    for i, q_anchor in enumerate(anchors_y):
        for j, f_anchor in enumerate(anchors_x):
            v = grid[
                grid["query_score_anchor"].eq(q_anchor)
                & grid["first_demo_anchor"].eq(f_anchor)
            ]["mean_score_shift"]
            z[i, j] = float(v.iloc[0]) if len(v) else np.nan
    text = np.where(np.isnan(z), "", np.char.mod("%.4f", z))
    z_abs = float(np.nanmax(np.abs(z))) if np.isfinite(z).any() else 1.0
    fig = go.Figure(data=go.Heatmap(
        z=z,
        x=[str(a) for a in anchors_x],
        y=[str(a) for a in anchors_y],
        text=text,
        texttemplate="%{text}",
        colorscale="RdBu",
        zmid=0.0,
        zmin=-z_abs,
        zmax=z_abs,
        colorbar=dict(title=dict(text="Score shift")),
        hovertemplate="Query score anchor: %{y}<br>First-demo score anchor: %{x}<br>Mean score shift: %{z:.5f}<extra></extra>",
    ))
    fig.update_layout(
        title=dict(
            text=(
                f"Feature {feature_idx}: mean score shift grid (α={alpha:g})"
                f"<br><sup>{token_mode}; only |first-demo − baseline| ≥ {ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS:g}</sup>"
            ),
            x=0.0,
            xanchor="left",
            font=dict(size=24, family=PLOT_FONT),
        ),
        xaxis=dict(title=axis_title("First demonstration score anchor", 18), tickfont=dict(size=15, family=PLOT_FONT)),
        yaxis=dict(title=axis_title("Test query score anchor", 18), autorange="reversed", tickfont=dict(size=15, family=PLOT_FONT)),
        width=760,
        height=680,
        template="plotly_white",
        font=dict(family=PLOT_FONT, size=14),
    )
    fig.show(config={"toImageButtonOptions": {"format": "png", "filename": f"stsb_anchor_pull_feature_{feature_idx}_score_shift_grid_min_distance", "width": 760, "height": 680, "scale": 4}})
    save_plotly_png_if_possible(fig, RESULT_DIR / f"stsb_anchor_pull_feature_{feature_idx}_score_shift_grid_min_distance.png", 760, 680)
    return fig


def plot_baseline_vs_steered_scores(feature_idx: Optional[int] = None, alpha: Optional[float] = None, token_mode: Optional[str] = None):
    sub, feature_idx, alpha, token_mode = _subset_effect(feature_idx, alpha, token_mode)
    sub = _filter_anchor_distance_for_plot(sub)
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=sub["baseline_pred_score_expected"],
        y=sub["steered_pred_score_expected"],
        mode="markers",
        marker=dict(size=5, opacity=0.5),
        text=[f"gold={v:.2f}, first={s:.2f}, |pull|={d:.2f}" for v, s, d in zip(sub["query_score"], sub["first_demo_score"], sub["baseline_distance_to_first_demo_score"])],
        hovertemplate="baseline=%{x:.3f}<br>steered=%{y:.3f}<br>%{text}<extra></extra>",
    ))
    fig.add_trace(go.Scatter(x=[0, 5], y=[0, 5], mode="lines", name="y=x"))
    fig.update_layout(
        title=dict(
            text=(
                f"Baseline vs. steered expected STS score, feature {feature_idx} (α={alpha:g})"
                f"<br><sup>{token_mode}; only |first-demo − baseline| ≥ {ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS:g}</sup>"
            ),
            x=0.0,
            xanchor="left",
            font=dict(size=24, family=PLOT_FONT),
        ),
        xaxis=dict(title=axis_title("Baseline expected score", 18), range=[0, 5], tickfont=dict(size=15, family=PLOT_FONT)),
        yaxis=dict(title=axis_title("Steered expected score", 18), range=[0, 5], tickfont=dict(size=15, family=PLOT_FONT)),
        width=720,
        height=650,
        template="plotly_white",
        font=dict(family=PLOT_FONT, size=14),
    )
    fig.show(config={"toImageButtonOptions": {"format": "png", "filename": f"stsb_anchor_pull_feature_{feature_idx}_baseline_vs_steered_min_distance", "width": 720, "height": 650, "scale": 4}})
    save_plotly_png_if_possible(fig, RESULT_DIR / f"stsb_anchor_pull_feature_{feature_idx}_baseline_vs_steered_min_distance.png", 720, 650)
    return fig


plot_top_anchor_pull_features(top_k=min(TOP_K_FEATURES_TO_DISPLAY, len(causal_summary_df)))
plot_token_mode_comparison(top_k_features=min(10, causal_summary_df["feature_idx"].nunique()))

if not causal_summary_df.empty:
    row = best_summary_row()
    top_feature_idx = int(row["feature_idx"])
    top_alpha = float(row["alpha"])
    top_token_mode = str(row["token_mode"])
    plot_score_shift_vs_anchor_pull(top_feature_idx, top_alpha, top_token_mode)
    plot_distance_reduction_vs_baseline_distance(top_feature_idx, top_alpha, top_token_mode)
    plot_score_shift_grid(top_feature_idx, top_alpha, top_token_mode)
    plot_baseline_vs_steered_scores(top_feature_idx, top_alpha, top_token_mode)

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

  distance_bin  mean_reduction  sem_reduction    n
0        1–1.5       -0.065019       0.075710  165
1        1.5–2        0.093791       0.082093  209
2        2–2.5        0.079867       0.092983  160
3        2.5–3       -0.416225       0.107009   94
4        3–3.5       -1.089950       0.084592   24
5        3.5–4       -1.139063       0.000000    1

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

In [ ]:
CAUSAL_INTERVENTION_TOKEN_MODES = [
    "all_query_tokens",
    "last_query_token",
    "assistant_generation_prefix_token",
    "last_prompt_token",
]

In [ ]:
[4724, 6396, 3901, 6537, 4140]

# Tuning

In [51]:
top_feature_idx = 4140
top_alpha = 10.0
top_token_mode = "last_prompt_token"
plot_score_shift_vs_anchor_pull(top_feature_idx, top_alpha, top_token_mode)
plot_distance_reduction_vs_baseline_distance(top_feature_idx, top_alpha, top_token_mode)
plot_score_shift_grid(top_feature_idx, top_alpha, top_token_mode)
plot_baseline_vs_steered_scores(top_feature_idx, top_alpha, top_token_mode)

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

  distance_bin  mean_reduction  sem_reduction    n
0        1–1.5        0.030466       0.052879  165
1        1.5–2       -0.021773       0.049315  209
2        2–2.5        0.084643       0.051082  160
3        2.5–3        0.437699       0.059133   94
4        3–3.5        0.908489       0.042705   24
5        3.5–4        1.135453       0.000000    1

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

In [47]:
def plot_score_shift_grid(feature_idx: Optional[int] = None, alpha: Optional[float] = None, token_mode: Optional[str] = None):
    sub, feature_idx, alpha, token_mode = _subset_effect(feature_idx, alpha, token_mode)
    sub = _filter_anchor_distance_for_plot(sub)
    grid = sub.groupby(["query_score_anchor", "first_demo_anchor"], as_index=False).agg(
        mean_score_shift=("delta_pred_score_expected", "mean"),
        mean_distance_reduction=("first_demo_score_distance_reduction", "mean"),
        n=("delta_pred_score_expected", "count"),
    )
    anchors_y = list(map(float, QUERY_SCORE_ANCHORS))
    anchors_x = list(map(float, VARIABLE_DEMO_SCORE_ANCHORS))
    z = np.full((len(anchors_y), len(anchors_x)), np.nan, dtype=float)
    for i, q_anchor in enumerate(anchors_y):
        for j, f_anchor in enumerate(anchors_x):
            v = grid[
                grid["query_score_anchor"].eq(q_anchor)
                & grid["first_demo_anchor"].eq(f_anchor)
            ]["mean_score_shift"]
            z[i, j] = float(v.iloc[0]) if len(v) else np.nan
    text = np.where(np.isnan(z), "", np.char.mod("%.4f", z))
    z_abs = float(np.nanmax(np.abs(z))) if np.isfinite(z).any() else 1.0
    
    fig = go.Figure(data=go.Heatmap(
        z=z,
        x=[str(a) for a in anchors_x],
        y=[str(a) for a in anchors_y],
        text=text,
        texttemplate="%{text}",
        colorscale="RdBu",
        zmid=0.0,
        zmin=-z_abs,
        zmax=z_abs,
        colorbar=dict(title=dict(text="Score shift")),
        hovertemplate="Query score anchor: %{y}<br>First-demo score anchor: %{x}<br>Mean score shift: %{z:.5f}<extra></extra>",
    ))

    # ADDED: Draw precise polygonal boundaries for the triangles
    N = len(anchors_x)  # Assuming a square grid (NxN)
    
    # 1. Upper Right Triangle Outline (Dark Blue)
    # Starts top-left of the region, draws the top edge, right edge, and staircases back
    path_ur = f"M 0.5,-0.5 L {N-0.5},-0.5 L {N-0.5},{N-1.5}"
    for k in range(N-1, 0, -1):
        path_ur += f" L {k-0.5},{k-0.5} L {k-0.5},{k-1.5}"
    path_ur += " Z"
    
    fig.add_shape(
        type="path",
        path=path_ur,
        line=dict(color="darkblue", width=3),
        fillcolor="rgba(0,0,0,0)"
    )

    # 2. Lower Left Triangle Outline (Dark Red)
    # Starts top-left of the region, draws the left edge, bottom edge, and staircases back
    path_ll = f"M -0.5,0.5 L -0.5,{N-0.5} L {N-1.5},{N-0.5}"
    for k in range(N-1, 0, -1):
        path_ll += f" L {k-0.5},{k-0.5} L {k-1.5},{k-0.5}"
    path_ll += " Z"
    
    fig.add_shape(
        type="path",
        path=path_ll,
        line=dict(color="darkred", width=3),
        fillcolor="rgba(0,0,0,0)"
    )

    fig.update_layout(
        title=dict(
            text=(
                f"Feature {feature_idx}: mean score shift grid (α={alpha:g})"
            ),
            x=0.0,
            xanchor="left",
            font=dict(size=24, family=PLOT_FONT),
        ),
        xaxis=dict(title=axis_title("First demonstration score anchor", 18), tickfont=dict(size=15, family=PLOT_FONT)),
        yaxis=dict(title=axis_title("Test query score anchor", 18), autorange="reversed", tickfont=dict(size=15, family=PLOT_FONT)),
        width=760,
        height=680,
#         template="plotly_white",
        font=dict(family=PLOT_FONT, size=14),
    )
    
    fig.show(config={"toImageButtonOptions": {"format": "png", "filename": f"stsb_anchor_pull_feature_{feature_idx}_score_shift_grid_min_distance", "width": 760, "height": 680, "scale": 4}})
    save_plotly_png_if_possible(fig, RESULT_DIR / f"stsb_anchor_pull_feature_{feature_idx}_score_shift_grid_min_distance.png", 760, 680)
    return fig

In [48]:
top_feature_idx = 4140
top_alpha = 10.0
top_token_mode = "all_query_tokens"
plot_score_shift_vs_anchor_pull(top_feature_idx, top_alpha, top_token_mode)
plot_distance_reduction_vs_baseline_distance(top_feature_idx, top_alpha, top_token_mode)
plot_score_shift_grid(top_feature_idx, top_alpha, top_token_mode)
plot_baseline_vs_steered_scores(top_feature_idx, top_alpha, top_token_mode)

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

  distance_bin  mean_reduction  sem_reduction    n
0        1–1.5       -0.000180       0.008992  165
1        1.5–2       -0.001725       0.008216  209
2        2–2.5        0.009377       0.008659  160
3        2.5–3       -0.001681       0.011393   94
4        3–3.5        0.037029       0.034576   24
5        3.5–4        0.111502       0.000000    1

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

In [49]:
top_feature_idx = 4140
top_alpha = 10.0
top_token_mode = "last_query_token"
plot_score_shift_vs_anchor_pull(top_feature_idx, top_alpha, top_token_mode)
plot_distance_reduction_vs_baseline_distance(top_feature_idx, top_alpha, top_token_mode)
plot_score_shift_grid(top_feature_idx, top_alpha, top_token_mode)
plot_baseline_vs_steered_scores(top_feature_idx, top_alpha, top_token_mode)

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

  distance_bin  mean_reduction  sem_reduction    n
0        1–1.5        0.010719       0.009874  165
1        1.5–2        0.012024       0.007702  209
2        2–2.5        0.003524       0.008805  160
3        2.5–3        0.004447       0.013093   94
4        3–3.5        0.024025       0.033800   24
5        3.5–4        0.157628       0.000000    1

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

Could not save PNG via kaleido; interactive figure still shown. Error: ValueError('\nImage export using the "kaleido" engine requires the Kaleido package,\nwhich can be installed using pip:\n\n    $ pip install --upgrade kaleido\n')

In [12]:

# ============================================================
# Compact summary for rebuttal/reporting
# ============================================================

summary_cols = [
    "feature_idx",
    "alpha",
    "token_mode",
    "anchor_pull_min_distance_for_analysis",
    "n_total_prompts_all_distances",
    "n_anchor_pull_analysis_prompts",
    "frac_prompts_kept_by_anchor_pull_filter",
    "mean_filtered_conditions_per_query",
    "mean_within_query_anchor_pull_corr",
    "sem_within_query_anchor_pull_corr",
    "frac_query_anchor_pull_corr_positive",
    "frac_query_anchor_pull_corr_gt_0p25",
    "global_anchor_pull_corr",
    "mean_first_demo_score_distance_reduction",
    "sem_first_demo_score_distance_reduction",
    "frac_prompts_first_demo_distance_reduction_positive",
    "mean_query_frac_prompts_shift_toward_first_demo",
    "mean_abs_delta_pred_score_expected",
    "mean_signed_shift_toward_first_demo_score",
    "mean_anchor_pull_dot_score",
    "mean_within_query_error_improvement_proximity_corr",
    "mean_squared_error_improvement",
    "mean_absolute_error_improvement",
]
summary_cols = [c for c in summary_cols if c in causal_summary_df.columns]

rebuttal_anchor_pull_top_df = causal_summary_df.head(TOP_K_FEATURES_TO_DISPLAY)[summary_cols].copy()
rebuttal_anchor_pull_top_path = RESULT_DIR / f"stsb_top_anchor_pull_causal_features_min_distance_{str(ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS).replace('.', 'p')}_latest.csv"
rebuttal_anchor_pull_top_df.to_csv(rebuttal_anchor_pull_top_path, index=False)

print("Saved top anchor-pull causal-feature table:", rebuttal_anchor_pull_top_path)
display(rebuttal_anchor_pull_top_df)

print("Best feature per token mode:")
display(
    causal_summary_df
    .sort_values("mean_within_query_anchor_pull_corr", ascending=False)
    .groupby("token_mode", as_index=False)
    .head(3)
    [summary_cols]
)

print("Interpretation template:")
print(
    f"For each fixed STS-B test query, we vary only the first demonstration's numeric similarity score. Main reported metrics filter out near-anchor cases with |first-demo score - baseline expected score| < {ANCHOR_PULL_MIN_DISTANCE_FOR_ANALYSIS}. "
    "For each SAE feature and each token span, we steer that feature one at a time and compute the model's "
    "expected numeric STS score before and after steering. The main diagnostic is corr(score shift, "
    "first-demo score - baseline expected score) within each fixed query. A positive value means that "
    "steering the feature tends to pull the model's numeric prediction toward the first demonstration's score."
)

Saved top anchor-pull causal-feature table: sts_b_proximity_outputs_qwen3_0_6b/stsb_score_anchor_pull_causal/layer_14/stsb_top_anchor_pull_causal_features_min_distance_1p0_latest.csv

,feature_idx,alpha,token_mode,anchor_pull_min_distance_for_analysis,n_total_prompts_all_distances,n_anchor_pull_analysis_prompts,frac_prompts_kept_by_anchor_pull_filter,mean_filtered_conditions_per_query,mean_within_query_anchor_pull_corr,sem_within_query_anchor_pull_corr,...,mean_first_demo_score_distance_reduction,sem_first_demo_score_distance_reduction,frac_prompts_first_demo_distance_reduction_positive,mean_query_frac_prompts_shift_toward_first_demo,mean_abs_delta_pred_score_expected,mean_signed_shift_toward_first_demo_score,mean_anchor_pull_dot_score,mean_within_query_error_improvement_proximity_corr,mean_squared_error_improvement,mean_absolute_error_improvement
0,6396,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.435020,0.042698,...,-0.068561,0.043850,0.454824,0.454896,1.076336,-0.042410,-0.196118,0.231434,-1.797096,-0.329863
1,6396,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.413592,0.041673,...,-0.044435,0.033510,0.462481,0.460208,0.753512,-0.036421,-0.160483,0.250180,-1.261016,-0.236212
2,4724,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.359493,0.041141,...,0.017429,0.011805,0.522205,0.521042,0.235543,0.017429,0.016648,0.241601,-0.260603,-0.047031
3,3901,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.212832,0.046210,...,-0.073658,0.026490,0.471669,0.468646,0.546108,-0.069870,-0.225700,0.134004,-0.973005,-0.183934
4,3901,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.176470,0.048678,...,-0.095244,0.030226,0.460949,0.458750,0.643424,-0.089602,-0.279053,0.101318,-1.158115,-0.218700
5,4140,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.172157,0.049497,...,0.119605,0.027006,0.551302,0.550938,0.664188,0.119757,0.336803,0.139485,-0.156137,-0.050313
6,4724,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.169345,0.046246,...,-0.016632,0.015287,0.456355,0.454479,0.302386,-0.016632,-0.056604,0.121021,-0.376192,-0.071983
7,4140,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.168693,0.048877,...,0.120290,0.028897,0.551302,0.550938,0.710731,0.120716,0.351792,0.143063,-0.169601,-0.049820
8,3901,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.123993,0.044548,...,0.006695,0.004454,0.528331,0.526042,0.078990,0.006695,0.017243,0.097761,-0.009613,-0.003616
9,3901,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.087054,0.045429,...,0.009261,0.004311,0.554364,0.557083,0.077377,0.009261,0.022960,0.064548,-0.011376,-0.004338
10,4140,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.083609,0.045295,...,0.009185,0.004688,0.511485,0.507292,0.082040,0.009185,0.019425,0.081260,-0.005445,-0.000784
11,6537,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.060428,0.047248,...,0.003908,0.004668,0.523737,0.513958,0.082219,0.003908,0.009498,0.037818,-0.013056,-0.003669
12,6396,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.047286,0.047284,...,0.006819,0.004507,0.506891,0.500417,0.081803,0.006819,0.014003,0.081211,-0.012299,-0.001456
13,6537,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.031291,0.047390,...,0.000657,0.004449,0.485452,0.480521,0.080594,0.000657,0.007303,0.042123,-0.019133,-0.005574
14,4140,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.029619,0.045587,...,0.002990,0.004567,0.499234,0.495938,0.079199,0.002990,0.009204,0.029808,-0.016665,-0.003121
15,4724,10.0,last_query_token,1.0,960,653,0.680208,4.08125,-0.013039,0.046983,...,0.002604,0.004623,0.505360,0.496875,0.082713,0.002604,0.005621,0.015091,0.000081,-0.001053
16,6396,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,-0.034328,0.046253,...,-0.003536,0.005000,0.474732,0.476562,0.090703,-0.003536,-0.008186,-0.007894,-0.007720,0.001466
17,6537,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,-0.074644,0.051028,...,-0.083490,0.031464,0.448698,0.449062,0.787445,-0.083490,-0.244423,-0.020258,-0.951670,-0.173707
18,4724,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,-0.118978,0.044475,...,-0.012750,0.005194,0.431853,0.431042,0.097350,-0.012750,-0.021376,-0.092592,-0.005049,0.000323
19,6537,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,-0.153004,0.049781,...,-0.112606,0.035950,0.448698,0.449062,0.909152,-0.111459,-0.317118,-0.073422,-1.203688,-0.215259

Best feature per token mode:

,feature_idx,alpha,token_mode,anchor_pull_min_distance_for_analysis,n_total_prompts_all_distances,n_anchor_pull_analysis_prompts,frac_prompts_kept_by_anchor_pull_filter,mean_filtered_conditions_per_query,mean_within_query_anchor_pull_corr,sem_within_query_anchor_pull_corr,...,mean_first_demo_score_distance_reduction,sem_first_demo_score_distance_reduction,frac_prompts_first_demo_distance_reduction_positive,mean_query_frac_prompts_shift_toward_first_demo,mean_abs_delta_pred_score_expected,mean_signed_shift_toward_first_demo_score,mean_anchor_pull_dot_score,mean_within_query_error_improvement_proximity_corr,mean_squared_error_improvement,mean_absolute_error_improvement
0,6396,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.435020,0.042698,...,-0.068561,0.043850,0.454824,0.454896,1.076336,-0.042410,-0.196118,0.231434,-1.797096,-0.329863
1,6396,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.413592,0.041673,...,-0.044435,0.033510,0.462481,0.460208,0.753512,-0.036421,-0.160483,0.250180,-1.261016,-0.236212
2,4724,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.359493,0.041141,...,0.017429,0.011805,0.522205,0.521042,0.235543,0.017429,0.016648,0.241601,-0.260603,-0.047031
3,3901,10.0,last_prompt_token,1.0,960,653,0.680208,4.08125,0.212832,0.046210,...,-0.073658,0.026490,0.471669,0.468646,0.546108,-0.069870,-0.225700,0.134004,-0.973005,-0.183934
4,3901,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.176470,0.048678,...,-0.095244,0.030226,0.460949,0.458750,0.643424,-0.089602,-0.279053,0.101318,-1.158115,-0.218700
6,4724,10.0,assistant_generation_prefix_token,1.0,960,653,0.680208,4.08125,0.169345,0.046246,...,-0.016632,0.015287,0.456355,0.454479,0.302386,-0.016632,-0.056604,0.121021,-0.376192,-0.071983
8,3901,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.123993,0.044548,...,0.006695,0.004454,0.528331,0.526042,0.078990,0.006695,0.017243,0.097761,-0.009613,-0.003616
9,3901,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.087054,0.045429,...,0.009261,0.004311,0.554364,0.557083,0.077377,0.009261,0.022960,0.064548,-0.011376,-0.004338
10,4140,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.083609,0.045295,...,0.009185,0.004688,0.511485,0.507292,0.082040,0.009185,0.019425,0.081260,-0.005445,-0.000784
11,6537,10.0,last_query_token,1.0,960,653,0.680208,4.08125,0.060428,0.047248,...,0.003908,0.004668,0.523737,0.513958,0.082219,0.003908,0.009498,0.037818,-0.013056,-0.003669
13,6537,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.031291,0.047390,...,0.000657,0.004449,0.485452,0.480521,0.080594,0.000657,0.007303,0.042123,-0.019133,-0.005574
14,4140,10.0,all_query_tokens,1.0,960,653,0.680208,4.08125,0.029619,0.045587,...,0.002990,0.004567,0.499234,0.495938,0.079199,0.002990,0.009204,0.029808,-0.016665,-0.003121

Interpretation template:
For each fixed STS-B test query, we vary only the first demonstration's numeric similarity score. Main reported metrics filter out near-anchor cases with |first-demo score - baseline expected score| < 1.0. For each SAE feature and each token span, we steer that feature one at a time and compute the model's expected numeric STS score before and after steering. The main diagnostic is corr(score shift, first-demo score - baseline expected score) within each fixed query. A positive value means that steering the feature tends to pull the model's numeric prediction toward the first demonstration's score.